import { useEffect, useRef, useState } from "react";
import {
  ArrowUpRight, Award, BookOpen, Bot, CalendarCheck, Check, ChevronRight, CircleHelp, Cloud,
  Compass, Database, Download, FileText, Globe2, GraduationCap, LayoutDashboard, LockKeyhole,
  Menu, Network, NotebookPen, Plus, Save, ShieldCheck, Sparkles, Target, TimerReset, Upload, X,
} from "lucide-react";
import { conceptCards, safeLabs, tracks } from "./data";
import { lessons } from "./lessonContent";
import { arabicConceptCards, arabicLessons, arabicSafeLabs, arabicTracks, copy, type Language } from "./locales";
import { completedStudyMinutes, isApprovedTrainingUrl, trackCompletion, validatePortfolioItem } from "./lib/domain";
import { useStoredState } from "./lib/storage";
import type { JournalEntry, LearningTrack, Lesson, PortfolioItem, StudyTask, View } from "./types";

type UiCopy = Record<keyof typeof copy.en, string>;

const nav = [
  ["dashboard", LayoutDashboard], ["roadmaps", Compass], ["labs", ShieldCheck], ["planner", CalendarCheck],
  ["journal", NotebookPen], ["portfolio", Award], ["library", BookOpen], ["ethics", LockKeyhole],
] as const;

function displayDate(language: Language, date = new Date()) {
  return new Intl.DateTimeFormat(language === "ar" ? "ar-IQ" : "en-US", { weekday: "long", day: "numeric", month: "long" }).format(date);
}

function downloadJson(filename: string, payload: unknown) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function App() {
  const [view, setView] = useStoredState<View>("c4e-view", "dashboard");
  const [language, setLanguage] = useStoredState<Language>("c4e-language", "ar");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [completedModules, setCompletedModules] = useStoredState<Record<string, boolean>>("c4e-modules", {});
  const [tasks, setTasks] = useStoredState<StudyTask[]>("c4e-tasks", []);
  const [journal, setJournal] = useStoredState<JournalEntry[]>("c4e-journal", []);
  const [portfolio, setPortfolio] = useStoredState<PortfolioItem[]>("c4e-portfolio", []);
  const [expandedTrack, setExpandedTrack] = useState("web");
  const t = copy[language] as UiCopy;
  const activeTracks = language === "ar" ? arabicTracks : tracks;
  const activeLessons: Record<string, Lesson> = language === "ar" ? arabicLessons : lessons;
  const activeLabs = language === "ar" ? arabicSafeLabs : safeLabs;
  const activeConcepts = language === "ar" ? arabicConceptCards : conceptCards;
  const labels: Record<View, string> = { dashboard: t.dashboard, roadmaps: t.roadmaps, labs: t.labs, planner: t.planner, journal: t.journal, portfolio: t.portfolio, library: t.library, ethics: t.ethics };
  const completedCount = Object.values(completedModules).filter(Boolean).length;
  const totalModules = activeTracks.reduce((sum, track) => sum + track.modules.length, 0);
  const overallProgress = Math.round((completedCount / totalModules) * 100);
  const currentTrack = activeTracks.find((track) => trackCompletion(track, completedModules) < 100) ?? activeTracks[0];
  const navigate = (next: View) => { setView(next); setMobileOpen(false); };
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.title = language === "ar" ? "Cyber 4 Ever | سايبر إلى الأبد" : "Cyber 4 Ever | Cybersecurity Learning Workspace";
  }, [language]);
  const content = {
    dashboard: <Dashboard language={language} t={t} tracks={activeTracks} currentTrack={currentTrack} completedModules={completedModules} overallProgress={overallProgress} completedCount={completedCount} totalModules={totalModules} tasks={tasks} journal={journal} onNavigate={navigate} />,
    roadmaps: <Roadmaps t={t} tracks={activeTracks} lessons={activeLessons} expandedTrack={expandedTrack} setExpandedTrack={setExpandedTrack} completedModules={completedModules} setCompletedModules={setCompletedModules} />,
    labs: <SafeLabs t={t} labs={activeLabs} onNavigate={navigate} />,
    planner: <Planner language={language} t={t} tracks={activeTracks} tasks={tasks} setTasks={setTasks} />,
    journal: <Journal t={t} journal={journal} setJournal={setJournal} />,
    portfolio: <Portfolio t={t} portfolio={portfolio} setPortfolio={setPortfolio} />,
    library: <Library t={t} concepts={activeConcepts} onNavigate={navigate} />,
    ethics: <Ethics language={language} t={t} />,
  }[view];

  return <div className="app-shell" dir={language === "ar" ? "rtl" : "ltr"}>
    <aside className={`sidebar ${mobileOpen ? "sidebar--open" : ""}`} aria-label={language === "ar" ? "التنقل الرئيسي" : "Primary navigation"}>
      <div className="brand-block">
        <div className="brand-mark"><Network size={23} strokeWidth={2.3} /></div>
        <div><strong>Cyber 4 Ever</strong><span>{t.brandTagline}</span></div>
        <button className="icon-button mobile-close" onClick={() => setMobileOpen(false)} aria-label={language === "ar" ? "إغلاق القائمة" : "Close navigation"}><X size={20} /></button>
      </div>
      <nav className="side-nav">{nav.map(([item, Icon]) => <button key={item} onClick={() => navigate(item)} className={`nav-item ${view === item ? "nav-item--active" : ""}`}><Icon size={18} /><span>{labels[item]}</span>{view === item && <ChevronRight size={16} className="nav-arrow" />}</button>)}</nav>
      <div className="sidebar-foot"><div className="privacy-card"><LockKeyhole size={17} /><div><strong>{t.private}</strong><span>{t.privateNote}</span></div></div><a href="https://github.com/9gkc/Cyber-4-Ever" target="_blank" rel="noreferrer" className="source-link"><span>GitHub</span><ArrowUpRight size={15} /></a></div>
    </aside>
    {mobileOpen && <button className="backdrop" aria-label={language === "ar" ? "إغلاق القائمة" : "Close navigation"} onClick={() => setMobileOpen(false)} />}
    <main className="main-area"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileOpen(true)} aria-label={language === "ar" ? "فتح القائمة" : "Open navigation"}><Menu size={21} /></button><div className="crumb"><span className="eyebrow">CYBER 4 EVER /</span><strong>{labels[view]}</strong></div><div className="top-actions"><button className="language-switch" type="button" title={t.language} aria-label={t.language} onClick={() => setLanguage(language === "ar" ? "en" : "ar")}>{t.languageShort}</button><div className="privacy-chip"><ShieldCheck size={15} />{t.private}</div></div></header><div className="content-wrap">{content}</div></main>
  </div>;
}

function Dashboard({ language, t, tracks, currentTrack, completedModules, overallProgress, completedCount, totalModules, tasks, journal, onNavigate }: { language: Language; t: UiCopy; tracks: LearningTrack[]; currentTrack: LearningTrack; completedModules: Record<string, boolean>; overallProgress: number; completedCount: number; totalModules: number; tasks: StudyTask[]; journal: JournalEntry[]; onNavigate: (view: View) => void }) {
  const nextModule = currentTrack.modules.find((module) => !completedModules[module.id]) ?? currentTrack.modules[0];
  const currentTrackProgress = trackCompletion(currentTrack, completedModules);
  return <>
    <section className="hero-grid"><div className="hero-copy"><div className="date-line"><span className="pulse-dot" />{displayDate(language)}</div><h1>{t.heroTitle}</h1><p>{t.heroBody}</p><div className="hero-actions"><button className="button button--primary" onClick={() => onNavigate("roadmaps")}>{t.startPath}<ChevronRight size={17} /></button><button className="button button--quiet" onClick={() => onNavigate("planner")}>{t.reviewPlan}<CalendarCheck size={17} /></button></div></div><div className="radar-card" aria-label={`${overallProgress}% ${t.progress}`}><div className="radar-grid" /><div className="radar-orbit orbit-1" /><div className="radar-orbit orbit-2" /><div className="radar-line" /><div className="radar-core"><span>{overallProgress}%</span><small>{t.progress}</small></div><div className="radar-label label-a">WEB</div><div className="radar-label label-b">SOC</div><div className="radar-label label-c">DFIR</div></div></section>
    <section className="stat-grid" aria-label={t.dashboard}><article className="stat-card"><div className="stat-icon aqua"><TimerReset size={20} /></div><strong>{completedStudyMinutes(tasks)}</strong><span>{t.completedMinutes}</span></article><article className="stat-card"><div className="stat-icon violet"><Check size={20} /></div><strong>{completedCount}<small>/{totalModules}</small></strong><span>{t.completedModules}</span></article><article className="stat-card"><div className="stat-icon amber"><Compass size={20} /></div><strong>{tracks.length}</strong><span>{t.activeTracks}</span></article><article className="stat-card stat-card--mini"><div className="mini-profile"><div className="avatar"><GraduationCap size={21} /></div><div><strong>{t.learner}</strong><span>{t.privacyFirst}</span></div></div></article></section>
    <section className="dashboard-grid"><article className="panel current-panel"><div className="panel-heading"><div><span className="eyebrow">{t.nowPath}</span><h2>{currentTrack.label}</h2></div><span className={`track-dot ${currentTrack.accent}`} /></div><div className="current-module"><div className="module-order">01</div><div><strong>{nextModule.title}</strong><p>{nextModule.outcome}</p></div><span className="duration">{nextModule.duration}</span></div><div className="progress-meta"><span>{t.pathMastery}</span><strong>{currentTrackProgress}%</strong></div><div className="progress-line"><span style={{ width: `${currentTrackProgress}%` }} /></div><button className="text-button" onClick={() => onNavigate("roadmaps")}>{t.explore}<ArrowUpRight size={16} /></button></article><article className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">{t.learningRecord}</span><h2>{t.keyMoments}</h2></div><button className="ghost-round" onClick={() => onNavigate("journal")} aria-label={t.openJournal}><Plus size={18} /></button></div>{journal.length === 0 ? <div className="empty-record"><NotebookPen size={24} /><p>{t.recordStart}</p><button className="text-button" onClick={() => onNavigate("journal")}>{t.openJournal}<ChevronRight size={16} /></button></div> : <div className="entry-list">{journal.slice(0, 3).map((entry) => <div className="entry-row" key={entry.id}><div className="entry-mark" /><div><strong>{entry.title}</strong><span>{entry.environment}</span></div><time>{entry.date}</time></div>)}</div>}</article></section>
    <section className="principle-banner"><div className="principle-icon"><ShieldCheck size={21} /></div><div><span className="eyebrow">{t.principle}</span><strong>{t.principleBody}</strong></div><button onClick={() => onNavigate("ethics")} className="text-button">{t.readBoundaries}<ArrowUpRight size={16} /></button></section>
  </>;
}

function Roadmaps({ t, tracks, lessons, expandedTrack, setExpandedTrack, completedModules, setCompletedModules }: { t: UiCopy; tracks: LearningTrack[]; lessons: Record<string, Lesson>; expandedTrack: string; setExpandedTrack: (value: string) => void; completedModules: Record<string, boolean>; setCompletedModules: (value: Record<string, boolean>) => void }) {
  const [activeLessonId, setActiveLessonId] = useState<string | null>(null);
  const activeModule = tracks.flatMap((track) => track.modules).find((module) => module.id === activeLessonId);
  const activeLesson = activeModule ? lessons[activeModule.id] : undefined;

  return <section className="page-section"><div className="page-heading"><span className="eyebrow">{t.pathsRoles}</span><h1>{t.learnSequence}</h1><p>{t.roadmapsBody}</p></div>{activeModule && activeLesson && <LessonDetail t={t} module={activeModule} lesson={activeLesson} completed={Boolean(completedModules[activeModule.id])} onClose={() => setActiveLessonId(null)} onComplete={() => setCompletedModules({ ...completedModules, [activeModule.id]: !completedModules[activeModule.id] })} />}<div className="track-list">{tracks.map((track, index) => { const isOpen = expandedTrack === track.id; const progress = trackCompletion(track, completedModules); const Icon = track.icon === "globe" ? Globe2 : track.icon === "shield" ? ShieldCheck : track.icon === "database" ? Database : Cloud; return <article className={`track-card track-card--${track.accent} ${isOpen ? "track-card--open" : ""}`} key={track.id}><button className="track-summary" onClick={() => setExpandedTrack(isOpen ? "" : track.id)} aria-expanded={isOpen}><div className="track-index">0{index + 1}</div><div className="track-symbol"><Icon size={22} /></div><div className="track-intro"><div className="track-title-row"><h2>{track.label}</h2><span>{track.level}</span></div><p>{track.description}</p></div><div className="track-progress"><strong>{progress}%</strong><span>{t.complete}</span></div><div className="expand-icon"><ChevronRight size={21} /></div></button>{isOpen && <div className="modules-panel"><div className="module-list">{track.modules.map((module, moduleIndex) => <button type="button" className={`module-row module-row--open ${completedModules[module.id] ? "module-row--complete" : ""}`} key={module.id} onClick={() => setActiveLessonId(module.id)}><span className="custom-check">{completedModules[module.id] && <Check size={13} />}</span><span className="module-number">{String(moduleIndex + 1).padStart(2, "0")}</span><span className="module-body"><strong>{module.title}</strong><small>{module.outcome}</small></span><span className="duration">{module.duration}</span><ChevronRight size={15} className="module-open-icon" /></button>)}</div><div className="track-footer"><div><span>{t.learningRule}</span><strong>{t.ruleBody}</strong></div><div className="progress-ring"><svg viewBox="0 0 36 36"><path className="ring-bg" d="M18 2.0845a 15.9155 15.9155 0 0 1 0 31.831a 15.9155 15.9155 0 0 1 0-31.831" /><path className="ring-value" strokeDasharray={`${progress}, 100`} d="M18 2.0845a 15.9155 15.9155 0 0 1 0 31.831a 15.9155 15.9155 0 0 1 0-31.831" /></svg><span>{progress}</span></div></div></div>}</article>; })}</div></section>;
}

function LessonDetail({ t, module, lesson, completed, onClose, onComplete }: { t: UiCopy; module: typeof tracks[number]["modules"][number]; lesson: typeof lessons[string]; completed: boolean; onClose: () => void; onComplete: () => void }) {
  return <article className="lesson-detail" aria-labelledby={`lesson-${module.id}`}><div className="lesson-detail__top"><div><span className="eyebrow">{t.activeLesson} · {module.duration}</span><h2 id={`lesson-${module.id}`}>{module.title}</h2><p>{lesson.overview}</p></div><button type="button" className="icon-button" aria-label={t.closeLesson} onClick={onClose}><X size={18} /></button></div><div className="lesson-objectives"><span className="eyebrow">{t.endCan}</span><ul>{lesson.objectives.map((objective) => <li key={objective}><Check size={14} />{objective}</li>)}</ul></div><div className="lesson-concepts">{lesson.concepts.map((concept) => <section className="lesson-concept" key={concept.title}><span className="eyebrow">{t.coreConcept}</span><h3>{concept.title}</h3><p>{concept.body}</p></section>)}</div><section className="lesson-practice"><div className="lesson-practice__symbol"><Target size={22} /></div><div><span className="eyebrow">{t.safePractice}</span><h3>{lesson.safePractice.title}</h3><ol>{lesson.safePractice.steps.map((step) => <li key={step}>{step}</li>)}</ol></div></section><section className="lesson-review"><div><span className="eyebrow">{t.checkUnderstanding}</span><h3>{lesson.review.prompt}</h3><p>{lesson.review.answer}</p></div><CircleHelp size={23} /></section><section className="lesson-boundaries"><LockKeyhole size={19} /><div><strong>{t.authorization}</strong><p>{lesson.boundaries}</p></div></section><div className="lesson-footer"><div className="lesson-references"><span className="eyebrow">{t.officialReferences}</span>{lesson.references.map((reference) => <a href={reference.url} target="_blank" rel="noreferrer" key={reference.url}>{reference.label}<ArrowUpRight size={14} /></a>)}</div><button type="button" className={`button ${completed ? "button--quiet" : "button--primary"}`} onClick={onComplete}>{completed ? t.markIncomplete : t.markComplete}<Check size={16} /></button></div></article>;
}

function SafeLabs({ t, labs, onNavigate }: { t: UiCopy; labs: typeof safeLabs; onNavigate: (view: View) => void }) {
  const approvedLabs = labs.filter((lab) => isApprovedTrainingUrl(lab.url));
  return <section className="page-section"><div className="page-heading"><span className="eyebrow">{t.labsKicker}</span><h1>{t.labsTitle}</h1><p>{t.labsBody}</p></div><div className="authorization-callout"><div className="callout-seal"><LockKeyhole size={24} /></div><div><strong>{t.beforeLab}</strong><p>{t.beforeLabBody}</p></div><button className="button button--quiet" onClick={() => onNavigate("ethics")}>{t.usagePolicy}<ArrowUpRight size={16} /></button></div><div className="lab-grid">{approvedLabs.map((lab, index) => <article className="lab-card" key={lab.name}><div className="lab-top"><span className="lab-tag">{lab.tag}</span><span className="lab-number">{String(index + 1).padStart(2, "0")}</span></div><div className="lab-symbol"><Bot size={26} /></div><h2>{lab.name}</h2><p>{lab.description}</p><div className="lab-fit"><strong>{t.bestFit}</strong><span>{lab.fit}</span></div><div className="lab-rule"><Check size={15} />{t.approved}</div><a className="text-button" href={lab.url} target="_blank" rel="noreferrer">{t.openResource}<ArrowUpRight size={16} /></a></article>)}</div><div className="lab-journal-bridge"><div><span className="eyebrow">{t.afterSession}</span><h2>{t.retainTitle}</h2><p>{t.retainBody}</p></div><button className="button button--primary" onClick={() => onNavigate("journal")}>{t.openJournal}<NotebookPen size={17} /></button></div></section>;
}

function Planner({ language, t, tracks, tasks, setTasks }: { language: Language; t: UiCopy; tracks: LearningTrack[]; tasks: StudyTask[]; setTasks: (value: StudyTask[]) => void }) {
  const [title, setTitle] = useState(""); const [track, setTrack] = useState("web"); const [minutes, setMinutes] = useState(45);
  const today = new Date().toISOString().slice(0, 10); const todayTasks = tasks.filter((task) => task.date === today); const completed = todayTasks.filter((task) => task.completed).length;
  function addTask(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3) return; setTasks([{ id: crypto.randomUUID(), title: title.trim(), track, minutes, completed: false, date: today }, ...tasks]); setTitle(""); }
  return <section className="page-section"><div className="page-heading inline-heading"><div><span className="eyebrow">{t.planKicker}</span><h1>{t.planTitle}</h1><p>{t.planBody}</p></div><div className="today-tile"><span>{displayDate(language)}</span><strong>{completed}/{todayTasks.length || 0}</strong><small>{t.tasksComplete}</small></div></div><div className="planner-grid"><form className="panel planner-form" onSubmit={addTask}><div className="panel-heading"><div><span className="eyebrow">{t.addSession}</span><h2>{t.addSession}</h2></div><Plus size={21} /></div><label>{t.whatLearn}<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={t.learnPlaceholder} maxLength={90} required /></label><div className="form-row"><label>{t.path}<select value={track} onChange={(event) => setTrack(event.target.value)}>{tracks.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>{t.minutes}<input type="number" min="15" max="240" value={minutes} onChange={(event) => setMinutes(Number(event.target.value))} /></label></div><button className="button button--primary" type="submit"><Save size={17} />{t.savePlan}</button></form><article className="panel plan-panel"><div className="panel-heading"><div><span className="eyebrow">{t.sessions}</span><h2>{t.doCheck}</h2></div><div className="time-total"><TimerReset size={16} />{todayTasks.reduce((sum, task) => sum + task.minutes, 0)}m</div></div>{todayTasks.length === 0 ? <div className="empty-record"><Target size={24} /><p>{t.addFirst}</p></div> : <div className="task-list">{todayTasks.map((task) => <label className={`task-row ${task.completed ? "task-row--done" : ""}`} key={task.id}><input type="checkbox" checked={task.completed} onChange={() => setTasks(tasks.map((item) => item.id === task.id ? { ...item, completed: !item.completed } : item))} /><span className="custom-check"><Check size={13} /></span><span className="task-track">{task.track.toUpperCase()}</span><span>{task.title}</span><small>{task.minutes}m</small><button type="button" onClick={() => setTasks(tasks.filter((item) => item.id !== task.id))} aria-label={t.removeTask}><X size={15} /></button></label>)}</div>}</article></div><div className="privacy-note"><LockKeyhole size={18} /><p>{t.planPrivate}</p></div></section>;
}

function Journal({ t, journal, setJournal }: { t: UiCopy; journal: JournalEntry[]; setJournal: (value: JournalEntry[]) => void }) {
  const [title, setTitle] = useState(""); const [environment, setEnvironment] = useState(""); const [lesson, setLesson] = useState(""); const fileRef = useRef<HTMLInputElement>(null);
  function addEntry(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3 || environment.trim().length < 3 || lesson.trim().length < 12) return; setJournal([{ id: crypto.randomUUID(), title: title.trim(), environment: environment.trim(), lesson: lesson.trim(), date: new Date().toISOString().slice(0, 10) }, ...journal]); setTitle(""); setEnvironment(""); setLesson(""); }
  function importJournal(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); if (Array.isArray(parsed) && parsed.every((entry) => typeof entry.title === "string" && typeof entry.lesson === "string")) setJournal(parsed as JournalEntry[]); } catch { /* Invalid imports are intentionally ignored. */ } }; reader.readAsText(file); event.target.value = ""; }
  return <section className="page-section"><div className="page-heading"><span className="eyebrow">{t.journalKicker}</span><h1>{t.journalTitle}</h1><p>{t.journalBody}</p></div><div className="journal-layout"><form className="journal-editor" onSubmit={addEntry}><div className="editor-top"><div><span className="eyebrow">{t.newNote}</span><h2>{t.remember}</h2></div><NotebookPen size={23} /></div><label>{t.clearTitle}<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={90} placeholder={t.titlePlaceholder} required /></label><label>{t.environment}<input value={environment} onChange={(event) => setEnvironment(event.target.value)} maxLength={70} placeholder={t.environmentPlaceholder} required /></label><label>{t.observation}<textarea value={lesson} onChange={(event) => setLesson(event.target.value)} maxLength={1200} placeholder={t.observationPlaceholder} required /></label><button className="button button--primary" type="submit"><Save size={17} />{t.saveLocal}</button><p className="form-hint"><LockKeyhole size={14} />{t.noSensitive}</p></form><div className="journal-record"><div className="journal-toolbar"><div><span className="eyebrow">{t.yourRecord}</span><h2>{journal.length} {t.notes}</h2></div><div><button className="toolbar-button" onClick={() => downloadJson("cyber-4-ever-journal.json", journal)}><Download size={16} />{t.export}</button><button className="toolbar-button" onClick={() => fileRef.current?.click()}><Upload size={16} />{t.import}</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={importJournal} /></div></div>{journal.length === 0 ? <div className="journal-empty"><FileText size={29} /><p>{t.noteStart}</p></div> : <div className="note-stack">{journal.map((entry) => <article className="journal-note" key={entry.id}><div className="note-meta"><span>{entry.environment}</span><time>{entry.date}</time></div><h3>{entry.title}</h3><p>{entry.lesson}</p><button onClick={() => setJournal(journal.filter((item) => item.id !== entry.id))}>{t.delete}</button></article>)}</div>}</div></div></section>;
}

function Portfolio({ t, portfolio, setPortfolio }: { t: UiCopy; portfolio: PortfolioItem[]; setPortfolio: (value: PortfolioItem[]) => void }) {
  const [kind, setKind] = useState<PortfolioItem["kind"]>("project"); const [title, setTitle] = useState(""); const [summary, setSummary] = useState(""); const [evidenceUrl, setEvidenceUrl] = useState(""); const [verified, setVerified] = useState(false); const [errors, setErrors] = useState<string[]>([]);
  function addItem(event: React.FormEvent) { event.preventDefault(); const candidate = { kind, title, summary, evidenceUrl, verified }; const nextErrors = validatePortfolioItem(candidate); setErrors(nextErrors); if (nextErrors.length > 0) return; setPortfolio([{ ...candidate, id: crypto.randomUUID() }, ...portfolio]); setTitle(""); setSummary(""); setEvidenceUrl(""); setVerified(false); }
  const kindLabels = { project: t.project, certificate: t.certificate, lab: t.labMilestone };
  return <section className="page-section"><div className="page-heading"><span className="eyebrow">{t.evidenceClaims}</span><h1>{t.portfolioTitle}</h1><p>{t.portfolioBody}</p></div><div className="portfolio-layout"><form className="panel portfolio-form" onSubmit={addItem}><div className="panel-heading"><div><span className="eyebrow">{t.addItem}</span><h2>{t.evidenceReview}</h2></div><Award size={23} /></div><label>{t.type}<select value={kind} onChange={(event) => setKind(event.target.value as PortfolioItem["kind"])}>{Object.entries(kindLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{t.clearTitle}<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={90} required /></label><label>{t.whatBuilt}<textarea value={summary} onChange={(event) => setSummary(event.target.value)} maxLength={500} required /></label><label>{t.evidenceLink}<input type="url" value={evidenceUrl} onChange={(event) => setEvidenceUrl(event.target.value)} placeholder="https://" /></label><label className="verify-checkbox"><input type="checkbox" checked={verified} onChange={(event) => setVerified(event.target.checked)} /><span className="custom-check"><Check size={13} /></span><span>{t.markEvidence}</span></label>{errors.length > 0 && <div className="form-errors">{errors.map((error) => <p key={error}>{error}</p>)}</div>}<button className="button button--primary" type="submit"><Plus size={17} />{t.addPortfolio}</button></form><section className="portfolio-preview"><div className="portfolio-header"><div className="portfolio-person"><div className="portfolio-avatar"><GraduationCap size={28} /></div><div><span>{t.studentProfile}</span><h2>{t.learnerName}</h2></div></div><button className="toolbar-button" onClick={() => downloadJson("cyber-4-ever-portfolio.json", portfolio)}><Download size={16} />{t.export}</button></div><div className="portfolio-principle"><Sparkles size={17} /><p>{t.noCertificates}</p></div>{portfolio.length === 0 ? <div className="portfolio-empty"><Award size={31} /><h3>{t.realMilestone}</h3><p>{t.milestoneBody}</p></div> : <div className="portfolio-cards">{portfolio.map((item) => <article className="portfolio-item" key={item.id}><div className="item-top"><span>{kindLabels[item.kind]}</span>{item.verified && <span className="verified"><ShieldCheck size={13} />{t.evidenceLinked}</span>}</div><h3>{item.title}</h3><p>{item.summary}</p><div className="item-bottom">{item.evidenceUrl ? <a href={item.evidenceUrl} target="_blank" rel="noreferrer">{t.viewEvidence}<ArrowUpRight size={14} /></a> : <span>{t.noExternal}</span>}<button onClick={() => setPortfolio(portfolio.filter((entry) => entry.id !== item.id))}>{t.remove}</button></div></article>)}</div>}</section></div></section>;
}

function Library({ t, concepts, onNavigate }: { t: UiCopy; concepts: typeof conceptCards; onNavigate: (view: View) => void }) {
  return <section className="page-section"><div className="page-heading"><span className="eyebrow">{t.understand}</span><h1>{t.conceptsTitle}</h1><p>{t.conceptsBody}</p></div><div className="concept-grid">{concepts.map((card, index) => <article className="concept-card" key={card.tag}><div className="concept-top"><span>{card.tag}</span><small>0{index + 1}</small></div><CircleHelp size={25} /><h2>{card.title}</h2><p>{card.detail}</p><div className="concept-footer"><span>{t.foundation}</span><button onClick={() => onNavigate("roadmaps")} aria-label={t.openRoadmaps}><ChevronRight size={18} /></button></div></article>)}</div><section className="reference-panel"><div><span className="eyebrow">{t.primaryRefs}</span><h2>{t.maintained}</h2><p>{t.refsBody}</p></div><div className="reference-links"><a href="https://niccs.cisa.gov/tools/nice-framework" target="_blank" rel="noreferrer">NICE Framework <ArrowUpRight size={15} /></a><a href="https://owasp.org/www-project-web-security-testing-guide/" target="_blank" rel="noreferrer">OWASP WSTG <ArrowUpRight size={15} /></a></div></section></section>;
}

function Ethics({ language, t }: { language: Language; t: UiCopy }) {
  const rows = language === "ar"
    ? [["مختبر مُعدّ للتدريب أو دورة تعليمية", t.allowed, "ok"], ["مشروعك أو بيئة تملك تفويضاً صريحاً لها", t.allowedScope, "ok"], ["موقع أو واجهة API أو شبكة بلا تفويض منك", t.notAllowed, "no"], ["بيانات شخصية أو أسرار أو رموز وصول", t.doNotStore, "no"]]
    : [["Purpose-built lab or training course", t.allowed, "ok"], ["Your project or explicitly authorized environment", t.allowedScope, "ok"], ["A site, API, or network without your authorization", t.notAllowed, "no"], ["Personal data, secrets, or access tokens", t.doNotStore, "no"]];
  return <section className="page-section"><div className="page-heading"><span className="eyebrow">{t.boundariesKicker}</span><h1>{t.ethicsTitle}</h1><p>{t.ethicsBody}</p></div><div className="ethics-grid"><article className="ethics-principles"><div className="ethic-icon"><ShieldCheck size={28} /></div><h2>{t.golden}</h2><blockquote>{t.goldenQuote}</blockquote><p>{t.goldenBody}</p></article><article className="boundary-table"><div className="table-head"><span>{t.context}</span><span>{t.decision}</span></div>{rows.map(([context, decision, status]) => <div className="table-row" key={context}><span>{context}</span><strong className={status === "ok" ? "allowed" : "blocked"}>{status === "ok" ? <Check size={15} /> : <X size={15} />}{decision}</strong></div>)}</article></div><div className="security-promise"><LockKeyhole size={22} /><div><h2>{t.privacyPromise}</h2><p>{t.privacyBody}</p></div></div></section>;
}
