import type { Lesson } from "./types";

export const lessons: Record<string, Lesson> = {
  "web-1": {
    overview: "Web security starts with understanding a normal request. Before you can judge a control, you need to recognize what the browser sends, what the server decides, and where state is stored.",
    objectives: ["Trace a browser request from URL to response.", "Distinguish headers, cookies, and body data.", "Explain why HTTPS protects data in transit but does not replace application controls."],
    concepts: [
      { title: "Request and response", body: "A request contains a method, a target, headers, and sometimes a body. A response carries a status code, headers, and content. Security review begins by asking which component is responsible for each decision." },
      { title: "State and cookies", body: "HTTP is stateless, so applications use cookies, tokens, or server-side sessions to remember context. A cookie is not proof that a user is allowed to perform every action; authorization must be checked by the server." },
    ],
    safePractice: { title: "Map a request in a purpose-built lab", steps: ["Open only an approved training application or a page you own.", "Use the browser developer tools Network panel to view one normal page-load request.", "Write down the method, status code, two response headers, and whether a cookie is present. Do not modify the request or target any external service." ] },
    review: { prompt: "What is the difference between a 401 and a 403 response?", answer: "A 401 commonly indicates that authentication is required or failed. A 403 means the server understood the request but refuses the current identity or context. The exact behavior is application-specific, so both should be interpreted with surrounding evidence." },
    boundaries: "Observe normal traffic only in an approved lab or a system you own. Do not replay, alter, or direct requests at systems outside your written authorization.",
    references: [{ label: "OWASP Web Security Testing Guide", url: "https://owasp.org/www-project-web-security-testing-guide/" }, { label: "MDN: HTTP overview", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview" }],
  },
  "web-2": {
    overview: "Authentication establishes who is interacting with a service. Session and authorization design determine what that identity can do over time. Strong designs consider both identity proof and every protected action.",
    objectives: ["Separate authentication, session management, and authorization.", "Recognize Secure, HttpOnly, and SameSite cookie attributes.", "Describe why the server must enforce access decisions."],
    concepts: [
      { title: "Three separate decisions", body: "Authentication verifies an asserted identity. Session management preserves a signed-in context. Authorization decides whether that identity may access a specific resource or action. Treating these as separate reviews prevents false assumptions." },
      { title: "Session defenses", body: "Cookie flags reduce common exposure paths: Secure limits transport to HTTPS, HttpOnly limits direct script access, and SameSite helps constrain cross-site cookie sending. These are layered protections, not substitutes for server-side checks." },
    ],
    safePractice: { title: "Build a defense checklist", steps: ["Choose an approved training application's sign-in page or a mock screen.", "List the identity, session, and authorization decision that must happen for a profile update.", "Write three defensive questions a reviewer should ask, such as whether the server rechecks ownership before changing data." ] },
    review: { prompt: "Why is a valid session not enough to authorize an action?", answer: "A session may prove that someone is signed in, but it does not prove they own every resource or hold every privilege. The application must evaluate authorization for the requested object and action on the server." },
    boundaries: "Do not attempt to access another account, change identifiers, or bypass sign-in controls. Use only intentionally designed lessons, demo accounts, or systems you personally administer.",
    references: [{ label: "OWASP Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" }, { label: "OWASP Session Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" }],
  },
  "web-3": {
    overview: "The OWASP Top 10 is an awareness resource that helps teams discuss common application-risk categories. Use it to connect a risk to preventive, detective, and recovery controls—not as a checklist for probing real sites.",
    objectives: ["Describe risk as a combination of context, likelihood, and impact.", "Map common application risks to defensive controls.", "Differentiate prevention, detection, and recovery activities."],
    concepts: [
      { title: "Risk-to-control thinking", body: "A useful security discussion identifies an asset, a failure mode, the expected impact, and a control. For example, server-side validation can prevent invalid input from reaching sensitive logic, while logging can help detect unexpected patterns." },
      { title: "Layered controls", body: "No single control handles every failure. Secure design combines input handling, authorization, secrets management, dependency maintenance, observability, and a response plan that matches the application context." },
    ],
    safePractice: { title: "Create a defensive control map", steps: ["Pick three fictional features: sign-in, file upload, and account settings.", "For each feature, name one preventive control, one detection signal, and one recovery action.", "Compare your map with OWASP guidance and record what you would clarify with a developer." ] },
    review: { prompt: "Why should a team avoid treating the OWASP Top 10 as a complete testing checklist?", answer: "It is an awareness document, not a complete model of an application's architecture, assets, threat model, or business rules. A mature review also considers the specific design and operating context." },
    boundaries: "Keep the exercise conceptual or inside a purpose-built lab. The platform does not authorize testing against public applications, employers, classmates, or third parties.",
    references: [{ label: "OWASP Top 10", url: "https://owasp.org/www-project-top-ten/" }, { label: "OWASP Application Security Verification Standard", url: "https://owasp.org/www-project-application-security-verification-standard/" }],
  },
  "web-4": {
    overview: "A professional finding is a decision-support document. It records a verified observation, explains the affected scope and plausible impact, and recommends a practical next action without exaggeration.",
    objectives: ["Separate evidence, observation, interpretation, and recommendation.", "Write a bounded impact statement.", "Use a reproducible, respectful finding structure."],
    concepts: [
      { title: "Evidence before conclusion", body: "Evidence can include a timestamp, a redacted request or screenshot, a lab version, and a short sequence of authorized steps. A conclusion should identify its confidence and any assumptions instead of presenting uncertainty as fact." },
      { title: "Actionable remediation", body: "Good remediation identifies a control objective and gives engineering teams an implementation direction. It should be specific enough to act on, but should not assume unverified infrastructure details." },
    ],
    safePractice: { title: "Write a training finding", steps: ["Use a completed lab scenario or a fictional case supplied by your course.", "Write four headings: observation, evidence, impact boundary, and recommended control.", "Remove credentials, personal data, and unsupported severity claims before saving it in your journal." ] },
    review: { prompt: "What makes an impact statement trustworthy?", answer: "It ties the impact to evidence and an explicit scope, distinguishes what was observed from what is possible, and avoids claims that cannot be supported by the authorized scenario." },
    boundaries: "Only document findings from training environments or scopes you are authorized to assess. Never publish sensitive evidence, credentials, or private user data.",
    references: [{ label: "OWASP Web Security Testing Guide", url: "https://owasp.org/www-project-web-security-testing-guide/" }, { label: "OWASP Vulnerability Disclosure Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.html" }],
  },
  "web-5": {
    overview: "Reporting is part of the security work. A careful report allows another authorized person to understand the environment, reproduce the observation, assess the evidence, and choose a remediation path.",
    objectives: ["Structure a concise lab report.", "Use redaction and scope labels consistently.", "Explain the difference between a learning record and a public disclosure."],
    concepts: [
      { title: "Reproducibility", body: "A report should state the permitted environment, time, account role, expected result, actual result, and defensive recommendation. Reproducible does not mean publishing unsafe details; it means an authorized reviewer can validate the evidence." },
      { title: "Disclosure discipline", body: "A lab note is private learning evidence. A real-world observation has additional legal, contractual, and safety considerations. Follow the program's policy and use its official reporting channel instead of public disclosure." },
    ],
    safePractice: { title: "Complete a report-quality review", steps: ["Open a journal entry from an approved lab.", "Add a scope label, a short evidence summary, and a remediation idea.", "Check that no password, token, personal data, or claim outside the lab's rules appears in the entry." ] },
    review: { prompt: "What is the purpose of a scope label in a report?", answer: "It identifies the authorized environment and limits how the evidence should be interpreted. It prevents readers from mistaking a training result for a claim about a production system." },
    boundaries: "Keep training evidence in your private journal unless the learning platform explicitly permits sharing. Respect reporting programs, local law, and the data-handling rules of every environment.",
    references: [{ label: "OWASP Vulnerability Disclosure Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.html" }, { label: "CISA Vulnerability Disclosure Policy Platform", url: "https://www.cisa.gov/vulnerability-disclosure-policy-template" }],
  },
  "soc-1": {
    overview: "SOC work starts with telemetry: records produced by systems, identities, endpoints, networks, and cloud services. A useful analyst knows what each source can and cannot show.",
    objectives: ["Identify common security telemetry sources.", "Explain why time synchronization and context matter.", "Distinguish a raw event from an analyst conclusion."],
    concepts: [
      { title: "Evidence sources", body: "Authentication logs, endpoint telemetry, DNS records, proxy logs, cloud audit records, and application logs each reveal different aspects of activity. Missing coverage should be recorded as a limitation, not silently assumed away." },
      { title: "Time and baseline", body: "A timestamp without a time zone or source clock can mislead a timeline. A baseline helps an analyst recognize unusual behavior, but unusual does not automatically mean malicious." },
    ],
    safePractice: { title: "Classify a supplied event set", steps: ["Use a sample event set from a training platform or a fabricated table.", "For each event, name the source type, timestamp, identity context, and one question it cannot answer.", "Write one sentence that distinguishes the observed event from your hypothesis." ] },
    review: { prompt: "Why is an alert not proof of an incident?", answer: "An alert is a detection signal based on logic and available data. It needs validation, context, and correlation before an analyst can decide whether it represents harmful activity or a benign explanation." },
    boundaries: "Analyze only datasets supplied for training or telemetry from systems you are authorized to operate. Do not collect or inspect classmates', employers', or public systems' data.",
    references: [{ label: "NIST SP 800-61 Rev. 3", url: "https://csrc.nist.gov/pubs/sp/800/61/r3/final" }, { label: "MITRE ATT&CK", url: "https://attack.mitre.org/" }],
  },
  "soc-2": {
    overview: "Triage is the disciplined process of deciding what to examine next. It balances urgency, confidence, scope, and available evidence without turning an uncertain signal into an unsupported incident claim.",
    objectives: ["Apply a repeatable triage sequence.", "Identify the evidence needed to validate an alert.", "Record an escalation decision and its rationale."],
    concepts: [
      { title: "Triage sequence", body: "Start with the alert's source, time, affected asset or identity, detection logic, and prior related activity. Then validate whether the data is complete, seek corroborating signals, and decide whether to close, monitor, or escalate." },
      { title: "Priority is contextual", body: "Priority reflects potential business impact, confidence, exposure, and time sensitivity. A high-volume alert may be low priority if it is understood; a small signal may matter if it affects a sensitive system." },
    ],
    safePractice: { title: "Triage a simulated alert", steps: ["Choose a blue-team training scenario with supplied telemetry.", "Write the alert facts first, then list three validation questions.", "Choose close, monitor, or escalate and explain the evidence that supports your decision." ] },
    review: { prompt: "What should be written before an escalation decision?", answer: "The known facts, the data source and time range, the affected scope, the validation performed, and the reason the current evidence supports escalation or another outcome." },
    boundaries: "Use supplied training cases only. Do not investigate external IP addresses, domains, or users merely because they appear in a sample alert.",
    references: [{ label: "CISA Incident Response Playbooks", url: "https://www.cisa.gov/resources-tools/resources/federal-government-cybersecurity-incident-and-vulnerability-response-playbooks" }, { label: "NIST SP 800-61 Rev. 3", url: "https://csrc.nist.gov/pubs/sp/800/61/r3/final" }],
  },
  "soc-3": {
    overview: "An incident timeline makes an investigation reviewable. It orders observations, preserves the source of each item, and distinguishes verified events from working hypotheses.",
    objectives: ["Build a timeline from provided evidence.", "Normalize timestamps and state assumptions.", "Connect related events without overstating causation."],
    concepts: [
      { title: "Timeline fields", body: "A usable entry has a normalized time, original time if different, source, event description, affected entity, and confidence. It can also include a link to the source artifact and a note about the analyst's interpretation." },
      { title: "Correlation is not certainty", body: "Events close in time can be related, but sequence alone does not prove cause. Record competing explanations and seek corroboration from independent sources where available." },
    ],
    safePractice: { title: "Build a three-event timeline", steps: ["Use three entries from a supplied scenario.", "Order them, label their time zone, and cite the source of each observation.", "Add one hypothesis and one piece of evidence you would need before treating the hypothesis as confirmed." ] },
    review: { prompt: "Why should an analyst preserve the original timestamp as well as a normalized one?", answer: "The original value supports traceability, while normalization helps compare events across systems. Keeping both makes later review and correction possible." },
    boundaries: "Do not use the platform to correlate real people, public data, or external infrastructure. Work only with simulated cases and authorized organizational telemetry.",
    references: [{ label: "NIST SP 800-61 Rev. 3", url: "https://csrc.nist.gov/pubs/sp/800/61/r3/final" }, { label: "MITRE ATT&CK", url: "https://attack.mitre.org/" }],
  },
  "soc-4": {
    overview: "Clear communication reduces risk during a response. It gives decision-makers enough context to act while respecting confidentiality, uncertainty, and the need to avoid harmful speculation.",
    objectives: ["Write a concise incident update.", "Communicate uncertainty responsibly.", "Identify when to use established escalation channels."],
    concepts: [
      { title: "A useful update", body: "A strong update states what happened, when it was observed, what is known, what is not known, the current scope, actions taken, and the next decision or owner. It uses plain language before technical detail." },
      { title: "Need-to-know handling", body: "Security information can be sensitive. Share it through the approved channel with the appropriate audience, and avoid posting raw data, personal information, or unverified attribution in public forums." },
    ],
    safePractice: { title: "Draft a simulated escalation", steps: ["Use a fictional or supplied scenario.", "Write a five-sentence update covering facts, scope, uncertainty, action, and next owner.", "Ask whether the update includes data that should be redacted before sharing." ] },
    review: { prompt: "How should uncertainty appear in an incident update?", answer: "State it directly. Separate confirmed observations from working hypotheses and name the next validation step. This improves decisions more than false certainty does." },
    boundaries: "Do not use real incident information in a public learning record. Follow your organization or lab provider's disclosure and escalation policy.",
    references: [{ label: "CISA Incident Response Playbooks", url: "https://www.cisa.gov/resources-tools/resources/federal-government-cybersecurity-incident-and-vulnerability-response-playbooks" }, { label: "NIST SP 800-61 Rev. 3", url: "https://csrc.nist.gov/pubs/sp/800/61/r3/final" }],
  },
  "dfir-1": {
    overview: "Digital forensics depends on integrity. Before analyzing an artifact, document where it came from, how it was handled, and how you will keep the original separate from your working copy.",
    objectives: ["Explain evidence integrity and chain-of-custody concepts.", "Separate original evidence from working material.", "Record scope, handler, time, and preservation assumptions."],
    concepts: [
      { title: "Integrity and traceability", body: "Integrity means that evidence has not been altered without record. Traceability means a reviewer can understand who handled it, when, how it was preserved, and which copy was analyzed." },
      { title: "Professional limits", body: "Technical handling does not replace legal or organizational requirements. Scope, authority, retention, and privacy rules must be confirmed before real evidence is collected or examined." },
    ],
    safePractice: { title: "Create a custody note for a sample file", steps: ["Use a file supplied by a training exercise or one you created yourself.", "Record the source, date, storage location, and that you will analyze a copy rather than overwrite the original.", "Write one question you would escalate to a supervisor or policy owner in a real investigation." ] },
    review: { prompt: "Why is it useful to preserve the original source separately from an analysis copy?", answer: "It protects the source from accidental modification and lets another authorized reviewer repeat the work against the same original material." },
    boundaries: "Do not acquire, copy, or inspect devices, accounts, media, or cloud data unless you own them or have explicit authority. Training artifacts only are in scope here.",
    references: [{ label: "NIST SP 800-86", url: "https://csrc.nist.gov/pubs/sp/800/86/final" }, { label: "NIST Digital Evidence", url: "https://www.nist.gov/digital-evidence" }],
  },
  "dfir-2": {
    overview: "Files carry context beyond their visible name. Metadata, paths, time values, and hashes can help explain an artifact, but each field needs careful interpretation and a known source.",
    objectives: ["Recognize common file context fields.", "Explain why timestamps need source and time-zone context.", "Separate an observed metadata value from a conclusion about behavior."],
    concepts: [
      { title: "Metadata as context", body: "File names, paths, sizes, hashes, owners, and timestamps can help create investigative questions. They do not independently establish intent, authorship, or maliciousness." },
      { title: "Time-value caution", body: "Different systems and file systems record time differently. A reliable note identifies the source, time zone, collection method, and any known limitations before comparing values." },
    ],
    safePractice: { title: "Read a safe metadata table", steps: ["Use a sample table provided by a DFIR lab or create one from your own harmless files.", "Identify the fields that are observations and list two conclusions that would be premature.", "Document which time zone or clock assumption you used." ] },
    review: { prompt: "Does a file timestamp prove who created a file?", answer: "No. It is one piece of context with system-specific behavior and possible limitations. Attribution needs additional corroborated evidence and an appropriate authorized process." },
    boundaries: "Do not access other people's files or devices. Use training images, public lab artifacts, or your own data with care for privacy.",
    references: [{ label: "NIST SP 800-86", url: "https://csrc.nist.gov/pubs/sp/800/86/final" }, { label: "NIST Digital Evidence Preservation", url: "https://www.nist.gov/itl/csd/secure-systems-and-applications/computer-forensics-tool-testing-program-cftt/digital" }],
  },
  "dfir-3": {
    overview: "Timelines help investigators see relationships across multiple artifacts. The goal is to make the evidence sequence easy to review, not to manufacture a story from incomplete data.",
    objectives: ["Combine timestamped observations into a transparent timeline.", "Identify gaps and conflicts in evidence.", "State confidence and alternate explanations."],
    concepts: [
      { title: "Cross-source timeline", body: "A timeline can combine file-system, log, network, and application evidence when each entry records its source and time basis. Conflicting entries should be preserved and investigated rather than silently removed." },
      { title: "Confidence and gaps", body: "A gap in data may result from retention limits, clock drift, disabled logging, or an event that did not occur. Describe the gap and its consequence for your conclusion." },
    ],
    safePractice: { title: "Correlate supplied artifacts", steps: ["Choose a DFIR training scenario with a small dataset.", "Place four observations in time order and cite their artifact sources.", "Add one gap, one alternate explanation, and one further source you would request in an authorized investigation." ] },
    review: { prompt: "What should you do when two sources appear to disagree?", answer: "Preserve both observations, check time zones and collection assumptions, and record the conflict. Do not force a conclusion until additional evidence can resolve or bound it." },
    boundaries: "Remain within the dataset and rules supplied by the lab. Do not search public systems, real identities, or unrelated external data to enrich a training case.",
    references: [{ label: "NIST SP 800-86", url: "https://csrc.nist.gov/pubs/sp/800/86/final" }, { label: "CyberDefenders Blue Team Labs", url: "https://cyberdefenders.org/blue-team-labs/" }],
  },
  "dfir-4": {
    overview: "A forensic summary communicates what the evidence supports, what it does not support, and what should happen next. The most valuable report is accurate, bounded, and understandable to its intended audience.",
    objectives: ["Write a concise investigation summary.", "Separate observations, assessments, and recommendations.", "Include limitations and evidence references."],
    concepts: [
      { title: "Evidence-led reporting", body: "Start with scope and questions, then present observations and their sources. An assessment connects the observations carefully; recommendations should be proportionate to the confidence and operating context." },
      { title: "Limits are professional", body: "A limitation can include missing logs, unavailable systems, a narrow time range, or a restricted scope. Naming it makes the report more useful and prevents readers from assuming more certainty than the evidence allows." },
    ],
    safePractice: { title: "Write a bounded case summary", steps: ["Use a completed training scenario.", "Write a one-paragraph scope, three observations with sources, one assessment, and two limitations.", "End with a defensive next step, such as preserving logs or reviewing an access control, without claiming unsupported attribution." ] },
    review: { prompt: "Why should limitations be included in a forensic summary?", answer: "They define what the evidence can support and help decision-makers understand uncertainty, gaps, and the need for additional authorized work." },
    boundaries: "Do not include personal data, credentials, or real-case details in a public portfolio. Use redacted training summaries only unless you have explicit permission to share.",
    references: [{ label: "NIST SP 800-86", url: "https://csrc.nist.gov/pubs/sp/800/86/final" }, { label: "NIST Digital Evidence", url: "https://www.nist.gov/digital-evidence" }],
  },
  "cloud-1": {
    overview: "Cloud security is a shared responsibility. The provider, the customer, and sometimes other parties each operate different layers, so the exact control owner depends on the service model and configuration.",
    objectives: ["Compare shared responsibilities across service models.", "Identify customer-controlled configuration areas.", "Explain why using a cloud service does not transfer all risk."],
    concepts: [
      { title: "Responsibilities change by service", body: "A provider may operate physical infrastructure and managed services, while the customer remains responsible for identities, data classification, configuration, and how services are used. Exact boundaries must be verified in the service documentation." },
      { title: "Security architecture", body: "A cloud design should identify assets, identities, data flows, logging, backups, key management, and recovery paths. The architecture makes it easier to decide who configures and monitors each control." },
    ],
    safePractice: { title: "Create a responsibility map", steps: ["Use a fictional file-sharing application running in a cloud training sandbox.", "Make two columns: provider-operated and customer-operated responsibilities.", "Mark three areas you would confirm in the provider documentation before deployment." ] },
    review: { prompt: "Why is 'the cloud provider secures everything' inaccurate?", answer: "Providers and customers operate different layers. Customers commonly retain responsibility for identity, data, configuration, and use of the services, while exact responsibilities depend on the model and contract." },
    boundaries: "Use only accounts, subscriptions, sandboxes, or class environments you are authorized to access. Follow provider terms, cost notices, and resource-cleanup instructions.",
    references: [{ label: "CISA Cloud Security Technical Reference Architecture", url: "https://www.cisa.gov/resources-tools/resources/cloud-security-technical-reference-architecture" }, { label: "NIST Cloud Computing Security Reference Architecture", url: "https://csrc.nist.gov/pubs/sp/500/299/ipd" }],
  },
  "cloud-2": {
    overview: "Identity is the control plane of cloud security. Least privilege means granting only the access needed for a justified task, for the shortest practical period, with reviewable ownership.",
    objectives: ["Describe least privilege and separation of duties.", "Identify risks in broad or shared access.", "Create a simple access-review checklist."],
    concepts: [
      { title: "Least privilege", body: "Start from the task, required resource, allowed actions, and duration. Prefer named identities and defined roles over shared credentials, and review access after a role or project changes." },
      { title: "Defense in depth for identity", body: "Strong authentication, role design, approval paths, logging, and periodic review work together. A single broad administrator role creates a large blast radius when it is misused or compromised." },
    ],
    safePractice: { title: "Review a fictional role", steps: ["Use a sample role policy from a cloud training course or write a fictional one.", "List the task it supports, the actions it needs, and any permissions that appear broader than that task.", "Propose a review owner and an expiry or review date." ] },
    review: { prompt: "What question should come before granting a permission?", answer: "What specific task requires this action on this resource for this duration? That question connects access to a legitimate need and exposes unnecessary breadth." },
    boundaries: "Do not request, modify, or test access in another person's cloud account. Practice with provider sandboxes, classroom tenants, or accounts you administer.",
    references: [{ label: "CSA Cloud Controls Matrix", url: "https://cloudsecurityalliance.org/research/cloud-controls-matrix" }, { label: "Microsoft Learn Security", url: "https://learn.microsoft.com/en-us/security/" }],
  },
  "cloud-3": {
    overview: "Secrets and configuration are operational security material. Treat keys, tokens, passwords, and sensitive connection details as protected data, and design systems so they are not embedded in code or exposed in logs.",
    objectives: ["Recognize common secret-exposure paths.", "Describe safe configuration-handling principles.", "Create a non-sensitive configuration review checklist."],
    concepts: [
      { title: "Secrets lifecycle", body: "A secret needs controlled creation, storage, use, rotation, and revocation. It should not be committed to source control, copied into screenshots, or shared in unprotected notes." },
      { title: "Configuration review", body: "Review public exposure, identity bindings, encryption settings, logging, retention, backups, and ownership. Record the intended state and verify it in the authorized environment rather than assuming defaults are safe." },
    ],
    safePractice: { title: "Inspect a fictional deployment checklist", steps: ["Use a sample configuration with placeholder values only.", "Identify where a secret should be stored and which logs might accidentally reveal it.", "Write three controls that would reduce the risk without placing any real credential in your notes." ] },
    review: { prompt: "Why is a secret in a source repository risky even if the repository is private?", answer: "Private access can change, copies and history may persist, and secrets can be exposed through logs, backups, collaborators, or later publication. Use approved secret-management mechanisms and rotate exposed values." },
    boundaries: "Never paste real API keys, passwords, access tokens, personal data, or customer configuration into Cyber 4 Ever. Use placeholders and revoke any accidentally exposed secret through the appropriate provider process.",
    references: [{ label: "OWASP Secrets Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html" }, { label: "CSA Cloud Controls Matrix", url: "https://cloudsecurityalliance.org/research/cloud-controls-matrix" }],
  },
  "cloud-4": {
    overview: "A control review turns security principles into repeatable questions. It focuses on assets, identities, data, monitoring, resilience, and ownership, then records the evidence and follow-up work.",
    objectives: ["Build a concise cloud control checklist.", "Connect controls to evidence and owners.", "Prioritize improvements without overstating compliance."],
    concepts: [
      { title: "Controls need evidence", body: "A control is more useful when its owner, intended outcome, evidence, review frequency, and exception process are known. A dashboard screenshot alone may be insufficient; record the authorized source and review context." },
      { title: "Continuous review", body: "Cloud environments change through identities, deployments, data flows, and service updates. Regular review and monitored change processes help keep intended controls aligned with the actual environment." },
    ],
    safePractice: { title: "Draft a sandbox control review", steps: ["Choose a provider's guided sandbox or a fictional cloud service.", "Check five areas: identity, data protection, logging, network exposure, and recovery ownership.", "For each area, record an expected control, a possible evidence source, and one question for the environment owner." ] },
    review: { prompt: "What is the difference between a control objective and evidence of a control?", answer: "A control objective states the security outcome sought, such as restricted administrative access. Evidence shows how an authorized reviewer can support that the control is configured, operating, and owned in a given environment." },
    boundaries: "A training checklist is not a certification, compliance attestation, or authorization to assess a real cloud tenant. Use it only in approved learning environments.",
    references: [{ label: "CSA Cloud Controls Matrix", url: "https://cloudsecurityalliance.org/research/cloud-controls-matrix" }, { label: "AWS Immersive Learning", url: "https://aws.amazon.com/training/digital/immersive-learning/" }],
  },
};
