import type { LearningTrack, Lesson } from "./types";

export type Language = "en" | "ar";

export const arabicTracks: LearningTrack[] = [
  {
    id: "web", label: "أمن تطبيقات الويب", description: "افهم طريقة عمل تطبيقات الويب وراجعها دفاعياً داخل مختبرات مصرح بها.", level: "من الأساسيات إلى المراجعة", accent: "aqua", icon: "globe",
    modules: [
      { id: "web-1", title: "كيف يعمل الويب وبروتوكول HTTP", duration: "90 د", outcome: "التعرّف إلى الطلبات والاستجابات وملفات الارتباط" },
      { id: "web-2", title: "المصادقة والجلسات", duration: "120 د", outcome: "فهم الدفاعات المرتبطة بالهوية والجلسة" },
      { id: "web-3", title: "أساسيات OWASP Top 10", duration: "150 د", outcome: "ربط المخاطر بالضوابط الوقائية" },
      { id: "web-4", title: "قراءة النتائج بمسؤولية", duration: "90 د", outcome: "كتابة ملاحظة نتيجة قابلة للتنفيذ" },
      { id: "web-5", title: "التقارير المهنية للمختبر", duration: "75 د", outcome: "بناء دليل واضح ضمن النطاق" },
    ],
  },
  {
    id: "soc", label: "الدفاع وعمليات مركز المراقبة", description: "مسار لتحليل السجلات وفرز التنبيهات وأساسيات الاستجابة للحوادث.", level: "من الكشف إلى الاستجابة", accent: "violet", icon: "shield",
    modules: [
      { id: "soc-1", title: "أساسيات الشبكات والسجلات", duration: "110 د", outcome: "التعرّف إلى مصادر الأدلة" },
      { id: "soc-2", title: "فرز التنبيهات", duration: "120 د", outcome: "ترتيب أولوية التنبيهات بهدوء" },
      { id: "soc-3", title: "الخط الزمني للحادث", duration: "90 د", outcome: "إنشاء تسلسل أدلة قابل للمراجعة" },
      { id: "soc-4", title: "التواصل والتصعيد", duration: "70 د", outcome: "كتابة تحديث واضح وآمن" },
    ],
  },
  {
    id: "forensics", label: "التحليل الجنائي الرقمي", description: "تعلّم حفظ الأدلة وتحليلها وتدوين الملاحظات من دون تغيير المصدر.", level: "من سلسلة الحيازة إلى التقرير", accent: "amber", icon: "database",
    modules: [
      { id: "dfir-1", title: "سلامة الأدلة وسلسلة الحيازة", duration: "100 د", outcome: "فهم توثيق المصدر" },
      { id: "dfir-2", title: "الملفات والبيانات الوصفية", duration: "105 د", outcome: "قراءة السياق من دون تغيير الدليل" },
      { id: "dfir-3", title: "بناء خط زمني", duration: "125 د", outcome: "ربط الأحداث زمنياً" },
      { id: "dfir-4", title: "ملخص التحقيق", duration: "80 د", outcome: "عرض الاستنتاجات وحدودها" },
    ],
  },
  {
    id: "cloud", label: "أمن الحوسبة السحابية", description: "افهم المسؤولية المشتركة والهوية والتهيئة الآمنة ضمن سياق تدريبي.", level: "من المفاهيم إلى الضوابط", accent: "blue", icon: "cloud",
    modules: [
      { id: "cloud-1", title: "نموذج المسؤولية المشتركة", duration: "75 د", outcome: "تحديد مسؤول حماية كل طبقة" },
      { id: "cloud-2", title: "الهوية وأقل الصلاحيات", duration: "115 د", outcome: "مواءمة الوصول مع الحاجة" },
      { id: "cloud-3", title: "الأسرار والتهيئة الآمنة", duration: "95 د", outcome: "تجنب تسرب الأسرار في الأمثلة" },
      { id: "cloud-4", title: "مراجعة الضوابط", duration: "90 د", outcome: "إنشاء قائمة تحقق دفاعية" },
    ],
  },
];

const refs = {
  wstg: { label: "دليل OWASP لاختبار أمن الويب", url: "https://owasp.org/www-project-web-security-testing-guide/" },
  top10: { label: "OWASP Top 10", url: "https://owasp.org/www-project-top-ten/" },
  asvs: { label: "معيار OWASP للتحقق من أمن التطبيقات", url: "https://owasp.org/www-project-application-security-verification-standard/" },
  auth: { label: "ورقة OWASP للمصادقة", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" },
  session: { label: "ورقة OWASP لإدارة الجلسات", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" },
  disclosure: { label: "ورقة OWASP للإفصاح عن الثغرات", url: "https://cheatsheetseries.owasp.org/cheatsheets/Vulnerability_Disclosure_Cheat_Sheet.html" },
  nistIr: { label: "NIST SP 800-61 Rev. 3", url: "https://csrc.nist.gov/pubs/sp/800/61/r3/final" },
  attack: { label: "MITRE ATT&CK", url: "https://attack.mitre.org/" },
  cisaPlaybooks: { label: "أدلة CISA للاستجابة للحوادث", url: "https://www.cisa.gov/resources-tools/resources/federal-government-cybersecurity-incident-and-vulnerability-response-playbooks" },
  nistForensics: { label: "NIST SP 800-86", url: "https://csrc.nist.gov/pubs/sp/800/86/final" },
  nistEvidence: { label: "NIST للأدلة الرقمية", url: "https://www.nist.gov/digital-evidence" },
  cisaCloud: { label: "مرجع CISA لبنية أمن السحابة", url: "https://www.cisa.gov/resources-tools/resources/cloud-security-technical-reference-architecture" },
  nistCloud: { label: "مرجع NIST لبنية أمن السحابة", url: "https://csrc.nist.gov/pubs/sp/500/299/ipd" },
  csa: { label: "مصفوفة ضوابط Cloud Security Alliance", url: "https://cloudsecurityalliance.org/research/cloud-controls-matrix" },
  secrets: { label: "ورقة OWASP لإدارة الأسرار", url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html" },
};

export const arabicLessons: Record<string, Lesson> = {
  "web-1": { overview: "يبدأ أمن الويب بفهم الطلب الطبيعي. قبل تقييم أي ضبط، تعرّف إلى ما يرسله المتصفح وما يقرره الخادم وأين تحفظ الحالة.", objectives: ["تتبّع طلب المتصفح من العنوان إلى الاستجابة.", "التمييز بين الرؤوس وملفات الارتباط وبيانات الجسم.", "شرح حماية HTTPS للبيانات أثناء النقل وحدودها."], concepts: [{ title: "الطلب والاستجابة", body: "يتضمن الطلب طريقة وعنواناً ورؤوساً وأحياناً جسماً، فيما تحمل الاستجابة رمز الحالة والرؤوس والمحتوى. تبدأ المراجعة بتحديد الجهة المسؤولة عن كل قرار." }, { title: "الحالة وملفات الارتباط", body: "HTTP عديم الحالة، لذا تستخدم التطبيقات ملفات ارتباط أو رموزاً أو جلسات على الخادم. وجود ملف ارتباط لا يمنح صلاحية لكل فعل؛ يجب أن يتحقق الخادم من التفويض." }], safePractice: { title: "ارسم خريطة لطلب في مختبر مخصص", steps: ["افتح تطبيقاً تدريبياً معتمداً أو صفحة تملكها.", "اعرض طلب تحميل صفحة عادي عبر لوحة Network في أدوات المتصفح.", "دوّن الطريقة ورمز الحالة ورأسين للاستجابة ووجود ملف ارتباط من دون تعديل الطلب." ] }, review: { prompt: "ما الفرق بين استجابة 401 و403؟", answer: "يشير 401 غالباً إلى أن المصادقة مطلوبة أو فشلت، أما 403 فيعني أن الخادم فهم الطلب لكنه يرفضه ضمن الهوية أو السياق الحالي. فسّر كليهما ضمن الأدلة المحيطة." }, boundaries: "راقب المرور الطبيعي في مختبر معتمد أو نظام تملكه فقط. لا تعِد إرسال الطلبات أو تعدّلها أو توجهها إلى أنظمة خارج تفويضك المكتوب.", references: [refs.wstg, { label: "MDN: نظرة عامة على HTTP", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview" }] },
  "web-2": { overview: "تحدد المصادقة هوية المتفاعل مع الخدمة، بينما تحدد إدارة الجلسة والتفويض ما تستطيع الهوية فعله مع مرور الوقت.", objectives: ["الفصل بين المصادقة وإدارة الجلسة والتفويض.", "التعرّف إلى خصائص Secure وHttpOnly وSameSite.", "شرح سبب فرض قرارات الوصول من الخادم."], concepts: [{ title: "ثلاثة قرارات مستقلة", body: "تتحقق المصادقة من الهوية، وتحفظ إدارة الجلسة السياق المسجّل، ويقرر التفويض السماح بفعل أو مورد محدد. الفصل بينها يمنع الافتراضات الخاطئة." }, { title: "دفاعات الجلسة", body: "تقلل خصائص ملف الارتباط مسارات التعرض الشائعة: Secure للنقل عبر HTTPS وHttpOnly لمنع الوصول المباشر بالبرامج النصية وSameSite لتقييد الإرسال عبر المواقع. وهي دفاعات طبقية لا بديل عن فحوص الخادم." }], safePractice: { title: "ابنِ قائمة تحقق دفاعية", steps: ["اختر صفحة تسجيل دخول تدريبية أو واجهة وهمية.", "حدّد قرارات الهوية والجلسة والتفويض اللازمة لتحديث ملف شخصي.", "اكتب ثلاثة أسئلة دفاعية، مثل تحقق الخادم من الملكية قبل تغيير البيانات." ] }, review: { prompt: "لماذا لا تكفي الجلسة الصحيحة لتفويض إجراء؟", answer: "قد تثبت الجلسة أن شخصاً سجّل دخوله، لكنها لا تثبت ملكيته لكل مورد أو امتلاكه لكل صلاحية. يجب أن يقيّم التطبيق التفويض للفعل والكائن المطلوبين على الخادم." }, boundaries: "لا تحاول دخول حساب آخر أو تغيير المعرّفات أو تجاوز تسجيل الدخول. استخدم دروساً مصممة عمداً أو حسابات تجريبية أو أنظمة تديرها بنفسك.", references: [refs.auth, refs.session] },
  "web-3": { overview: "OWASP Top 10 مورد توعوي يساعد الفرق على مناقشة فئات المخاطر الشائعة. استخدمه لربط الخطر بضوابط وقائية وكاشفة واستردادية، لا كقائمة لفحص مواقع حقيقية.", objectives: ["وصف الخطر وفق السياق والاحتمال والأثر.", "ربط مخاطر التطبيقات بالضوابط الدفاعية.", "تمييز أنشطة المنع والكشف والاسترداد."], concepts: [{ title: "التفكير من الخطر إلى الضبط", body: "تحدد المناقشة المفيدة أصلاً مهماً ونمط فشل وأثراً متوقعاً وضبطاً. مثال ذلك أن التحقق الخادمي من الإدخال يمنع وصول قيم غير صالحة إلى منطق حساس، بينما تساعد السجلات في كشف الأنماط غير المتوقعة." }, { title: "ضوابط طبقية", body: "لا يعالج ضبط واحد كل الفشل. يجمع التصميم الآمن بين معالجة الإدخال والتفويض وإدارة الأسرار وصيانة التبعيات والمراقبة وخطة الاستجابة المناسبة للسياق." }], safePractice: { title: "أنشئ خريطة ضوابط دفاعية", steps: ["اختر ثلاث ميزات خيالية: تسجيل الدخول ورفع ملف وإعدادات الحساب.", "سمِّ لكل ميزة ضبطاً وقائياً وإشارة كشف وإجراء استرداد.", "قارن الخريطة بإرشادات OWASP وسجل ما ستوضحه للمطور." ] }, review: { prompt: "لماذا لا ينبغي للفريق اعتبار OWASP Top 10 قائمة اختبار كاملة؟", answer: "هو مستند توعوي، وليس نموذجاً كاملاً لبنية التطبيق أو أصوله أو نموذج تهديداته أو قواعد أعماله. تدرس المراجعة الناضجة التصميم والسياق التشغيلي المحددين." }, boundaries: "أبقِ التمرين مفاهيمياً أو داخل مختبر مصمم للتدريب. لا تمنح المنصة إذناً لاختبار التطبيقات العامة أو جهة العمل أو الزملاء أو أطراف ثالثة.", references: [refs.top10, refs.asvs] },
  "web-4": { overview: "النتيجة المهنية وثيقة تدعم القرار: تسجل ملاحظة مؤكدة وتشرح نطاقها وأثرها المعقول وتقترح خطوة عملية من دون مبالغة.", objectives: ["الفصل بين الدليل والملاحظة والتفسير والتوصية.", "كتابة بيان أثر محدد النطاق.", "استخدام بنية نتيجة قابلة للتكرار ومحترمة."], concepts: [{ title: "الدليل قبل الاستنتاج", body: "قد يتضمن الدليل طابعاً زمنياً أو طلباً منقحاً أو لقطة شاشة وإصدار المختبر وتسلسلاً قصيراً من خطوات مصرح بها. يجب أن يحدد الاستنتاج درجة ثقته وافتراضاته." }, { title: "المعالجة القابلة للتنفيذ", body: "تحدد المعالجة الجيدة هدف الضبط وتعطي الفريق الهندسي اتجاهاً للتنفيذ، من دون افتراض تفاصيل بنية تحتية لم تتحقق." }], safePractice: { title: "اكتب نتيجة تدريبية", steps: ["استخدم سيناريو مختبر مكتمل أو حالة خيالية من دورتك.", "اكتب عناوين: الملاحظة والدليل وحد الأثر والضبط المقترح.", "احذف بيانات الاعتماد والبيانات الشخصية وادعاءات الخطورة غير المدعومة قبل الحفظ." ] }, review: { prompt: "ما الذي يجعل بيان الأثر موثوقاً؟", answer: "يربط الأثر بالدليل والنطاق الصريح، ويفرق بين ما شوهد وما يمكن أن يحدث، ويتجنب الادعاءات غير المدعومة بالسيناريو المصرح." }, boundaries: "وثّق نتائج البيئات التدريبية أو النطاقات المصرح بتقييمها فقط. لا تنشر أدلة حساسة أو بيانات اعتماد أو بيانات مستخدمين خاصة.", references: [refs.wstg, refs.disclosure] },
  "web-5": { overview: "إعداد التقرير جزء من العمل الأمني. يتيح التقرير الدقيق لمراجع مصرح فهم البيئة وتكرار الملاحظة وتقييم الدليل واختيار مسار معالجة.", objectives: ["بناء تقرير مختبر موجز.", "استخدام التنقيح وتسميات النطاق باتساق.", "شرح الفرق بين سجل تعلم وإفصاح عام."], concepts: [{ title: "قابلية التكرار", body: "يذكر التقرير البيئة المسموح بها والوقت ودور الحساب والنتيجة المتوقعة والفعلية والتوصية الدفاعية. لا تعني قابلية التكرار نشر تفاصيل غير آمنة، بل تمكين المراجع المصرح من التحقق." }, { title: "انضباط الإفصاح", body: "ملاحظة المختبر دليل تعلم خاص. أما ملاحظة الواقع فلها اعتبارات قانونية وتعاقدية وسلامة إضافية؛ اتبع سياسة البرنامج وقناة الإبلاغ الرسمية." }], safePractice: { title: "أكمل مراجعة جودة تقرير", steps: ["افتح إدخالاً من مختبر معتمد.", "أضف تسمية نطاق وملخص دليل وفكرة معالجة.", "تحقق من عدم وجود كلمة مرور أو رمز أو بيانات شخصية أو ادعاء خارج قواعد المختبر." ] }, review: { prompt: "ما هدف تسمية النطاق في التقرير؟", answer: "تحدد البيئة المصرح بها وحدود تفسير الدليل، وتمنع الخلط بين نتيجة تدريبية وادعاء عن نظام إنتاجي." }, boundaries: "احتفظ بأدلة التدريب في دفتر خاص إلا إذا سمحت المنصة التعليمية صراحة بالمشاركة. احترم برامج الإبلاغ والقانون المحلي وقواعد معالجة البيانات.", references: [refs.disclosure, { label: "منصة CISA لسياسة الإفصاح عن الثغرات", url: "https://www.cisa.gov/vulnerability-disclosure-policy-template" }] },
  "soc-1": { overview: "تبدأ أعمال مركز المراقبة بالقياس عن بُعد: سجلات الأنظمة والهويات والأجهزة والشبكات والخدمات السحابية. يعرف المحلل الجيد ما الذي يظهره كل مصدر وما الذي لا يظهره.", objectives: ["تحديد مصادر القياس الأمني الشائعة.", "شرح أهمية مزامنة الوقت والسياق.", "تمييز الحدث الخام من استنتاج المحلل."], concepts: [{ title: "مصادر الأدلة", body: "تكشف سجلات المصادقة والأجهزة الطرفية وDNS والوكيل والتدقيق السحابي والتطبيقات جوانب مختلفة من النشاط. سجّل نقص التغطية كحد لا كافتراض مخفي." }, { title: "الوقت وخط الأساس", body: "قد يضلل الطابع الزمني بلا منطقة زمنية أو ساعة مصدر. يساعد خط الأساس في تمييز غير المعتاد، لكن غير المعتاد ليس خبيثاً تلقائياً." }], safePractice: { title: "صنّف مجموعة أحداث مقدمة", steps: ["استخدم مجموعة أحداث تدريبية أو جدولاً خيالياً.", "سمِّ مصدر كل حدث ووقته وسياق الهوية وسؤالاً لا يجيب عنه.", "اكتب جملة تفرق بين الحدث المرصود وفرضيتك." ] }, review: { prompt: "لماذا لا يثبت التنبيه وجود حادث؟", answer: "التنبيه إشارة كشف مبنية على منطق وبيانات متاحة، ويحتاج إلى تحقق وسياق وربط قبل تقرير ما إذا كان نشاطاً ضاراً أو تفسيراً سليماً." }, boundaries: "حلل مجموعات بيانات تدريبية أو قياساً لأنظمة مخول بتشغيلها فقط. لا تجمع أو تفحص بيانات زملاء أو أصحاب عمل أو أنظمة عامة.", references: [refs.nistIr, refs.attack] },
  "soc-2": { overview: "الفرز عملية منضبطة لتقرير ما الذي يفحص تالياً. يوازن بين الإلحاح والثقة والنطاق والدليل المتاح من دون تحويل إشارة غير مؤكدة إلى ادعاء حادث.", objectives: ["تطبيق تسلسل فرز قابل للتكرار.", "تحديد الدليل المطلوب للتحقق من التنبيه.", "تسجيل قرار التصعيد وسببه."], concepts: [{ title: "تسلسل الفرز", body: "ابدأ بالمصدر والوقت والأصل أو الهوية المتأثرة ومنطق الكشف والنشاط السابق. تحقق من اكتمال البيانات وابحث عن إشارات مؤيدة ثم قرر الإغلاق أو المراقبة أو التصعيد." }, { title: "الأولوية سياقية", body: "تعكس الأولوية أثر الأعمال المحتمل والثقة والتعرض وحساسية الوقت. قد يكون تنبيه كثيف منخفض الأولوية إذا فهم، وقد تكون إشارة صغيرة مهمة إذا أثرت على نظام حساس." }], safePractice: { title: "افرز تنبيهاً محاكياً", steps: ["اختر سيناريو فريق أزرق بتليمترية مقدمة.", "اكتب حقائق التنبيه أولاً ثم ثلاث أسئلة تحقق.", "اختر الإغلاق أو المراقبة أو التصعيد واشرح الدليل الداعم." ] }, review: { prompt: "ما الذي يكتب قبل قرار التصعيد؟", answer: "الحقائق المعروفة ومصدر البيانات والفترة الزمنية والنطاق المتأثر والتحقق المنجز وسبب دعم الدليل للتصعيد أو نتيجة أخرى." }, boundaries: "استخدم حالات التدريب المقدمة فقط. لا تحقق في عناوين IP أو نطاقات أو مستخدمين خارجيين لمجرد ظهورهم في تنبيه نموذجي.", references: [refs.cisaPlaybooks, refs.nistIr] },
  "soc-3": { overview: "يجعل الخط الزمني للحادث التحقيق قابلاً للمراجعة: يرتب الملاحظات ويحفظ مصدر كل عنصر ويفصل الحدث المؤكد عن الفرضية.", objectives: ["بناء خط زمني من دليل مقدم.", "توحيد الطوابع الزمنية وتحديد الافتراضات.", "ربط الأحداث من دون المبالغة في السببية."], concepts: [{ title: "حقول الخط الزمني", body: "يحتوي الإدخال المفيد على وقت موحد والوقت الأصلي والمصدر ووصف الحدث والكيان المتأثر ودرجة الثقة، ويمكن أن يضم رابط الأثر وملاحظة التفسير." }, { title: "الارتباط ليس يقيناً", body: "قد ترتبط الأحداث القريبة زمنياً، لكن التسلسل لا يثبت السبب. سجّل التفسيرات المنافسة وابحث عن أدلة مستقلة مؤيدة." }], safePractice: { title: "أنشئ خطاً زمنياً بثلاثة أحداث", steps: ["استخدم ثلاثة إدخالات من سيناريو مقدم.", "رتبها وحدد منطقتها الزمنية ومصدر كل ملاحظة.", "أضف فرضية ودليلاً تحتاجه قبل اعتبارها مؤكدة." ] }, review: { prompt: "لماذا تحفظ الوقت الأصلي إضافة إلى الوقت الموحّد؟", answer: "يدعم الوقت الأصلي التتبع، بينما يجعل التوحيد المقارنة ممكنة. وجودهما يكشف الافتراضات ومشكلات تحويل الوقت." }, boundaries: "لا تستخدم المنصة لربط أشخاص حقيقيين أو بيانات عامة أو بنية خارجية. اعمل في حالات محاكاة وقياس تنظيمي مصرح فقط.", references: [refs.nistIr, refs.attack] },
  "soc-4": { overview: "يقلل التواصل الواضح الخطر أثناء الاستجابة، فيمنح صناع القرار سياقاً كافياً مع احترام السرية وعدم اليقين وتجنب التخمين الضار.", objectives: ["كتابة تحديث حادث موجز.", "التواصل مع عدم اليقين بمسؤولية.", "معرفة متى تستخدم قنوات التصعيد المعتمدة."], concepts: [{ title: "التحديث المفيد", body: "يذكر التحديث ما حدث ومتى لوحظ وما هو معلوم وغير معلوم والنطاق الحالي والإجراء المتخذ والقرار أو المالك التالي، بلغة واضحة قبل التفاصيل التقنية." }, { title: "المشاركة حسب الحاجة", body: "قد تكون المعلومات الأمنية حساسة. شاركها عبر القناة المعتمدة مع الجمهور المناسب، وتجنب نشر البيانات الخام أو المعلومات الشخصية أو الإسناد غير المؤكد في المنتديات العامة." }], safePractice: { title: "صغ تصعيداً محاكياً", steps: ["استخدم سيناريو خيالياً أو مقدماً.", "اكتب خمسة أسطر تشمل الحقائق والنطاق وعدم اليقين والإجراء والمالك التالي.", "اسأل إن كان التحديث يحتوي بيانات يجب تنقيحها قبل المشاركة." ] }, review: { prompt: "كيف ينبغي أن يظهر عدم اليقين في تحديث الحادث؟", answer: "اذكره مباشرة، وافصل الملاحظات المؤكدة عن فرضيات العمل وسمّ خطوة التحقق التالية. ذلك يحسن القرار أكثر من اليقين الزائف." }, boundaries: "لا تستخدم معلومات حادث حقيقية في سجل تعلم عام. اتبع سياسة الإفصاح والتصعيد لمنظمتك أو موفر المختبر.", references: [refs.cisaPlaybooks, refs.nistIr] },
  "dfir-1": { overview: "يعتمد التحليل الجنائي الرقمي على السلامة. قبل تحليل أي أثر، وثق مصدره وكيف عولج وكيف ستفصل الأصل عن نسخة العمل.", objectives: ["شرح سلامة الأدلة وسلسلة الحيازة.", "فصل الدليل الأصلي عن مواد العمل.", "تسجيل النطاق والمعالج والوقت وافتراضات الحفظ."], concepts: [{ title: "السلامة وقابلية التتبع", body: "تعني السلامة أن الدليل لم يتغير بلا سجل، وتعني قابلية التتبع أن يفهم المراجع من عالجه ومتى وكيف حفظ وأي نسخة حللت." }, { title: "حدود المهنة", body: "لا تغني المعالجة التقنية عن المتطلبات القانونية والتنظيمية. يجب تأكيد النطاق والصلاحية والاحتفاظ والخصوصية قبل جمع دليل حقيقي أو فحصه." }], safePractice: { title: "أنشئ ملاحظة حيازة لملف نموذجي", steps: ["استخدم ملفاً من تمرين تدريبي أو أنشأته بنفسك.", "سجل المصدر والتاريخ ومكان التخزين وأنك ستحلل نسخة لا الأصل.", "اكتب سؤالاً تصعده للمشرف أو مالك السياسة في تحقيق فعلي." ] }, review: { prompt: "لماذا يحفظ المصدر الأصلي منفصلاً عن نسخة التحليل؟", answer: "لحماية المصدر من التعديل العرضي وتمكين مراجع مخول آخر من تكرار العمل على المادة الأصلية نفسها." }, boundaries: "لا تحصل على أجهزة أو حسابات أو وسائط أو بيانات سحابية ولا تنسخها أو تفحصها إلا إذا كنت تملكها أو لديك صلاحية صريحة. آثار التدريب فقط ضمن النطاق.", references: [refs.nistForensics, refs.nistEvidence] },
  "dfir-2": { overview: "تحمل الملفات سياقاً يتجاوز اسمها الظاهر. تساعد البيانات الوصفية والمسارات والأوقات والبصمات في تفسير الأثر، لكن كل حقل يحتاج تفسيراً ومصدراً معروفاً.", objectives: ["التعرف إلى حقول سياق الملف الشائعة.", "شرح الحاجة إلى مصدر ومنطقة زمنية للطوابع.", "فصل قيمة البيانات الوصفية المرصودة عن استنتاج السلوك."], concepts: [{ title: "البيانات الوصفية كسياق", body: "يمكن للأسماء والمسارات والأحجام والبصمات والمالكين والطوابع الزمنية أن تولد أسئلة تحقيق، لكنها لا تثبت وحدها النية أو المؤلف أو الخبث." }, { title: "حذر قيم الوقت", body: "تسجل الأنظمة وأنظمة الملفات الوقت بطرق مختلفة. تحدد الملاحظة الموثوقة المصدر والمنطقة الزمنية وطريقة الجمع والقيود قبل المقارنة." }], safePractice: { title: "اقرأ جدول بيانات وصفية آمناً", steps: ["استخدم جدولاً من مختبر DFIR أو أنشئ واحداً من ملفاتك غير الحساسة.", "حدد الحقول التي تعد ملاحظات واذكر استنتاجين متسرعين.", "وثق المنطقة الزمنية أو افتراض الساعة المستخدم." ] }, review: { prompt: "هل يثبت طابع الملف الزمني من أنشأه؟", answer: "لا. إنه جزء واحد من السياق بسلوك يعتمد على النظام وقيود محتملة. يحتاج الإسناد إلى دليل إضافي مؤيد وإجراء مصرح مناسب." }, boundaries: "لا تصل إلى ملفات أو أجهزة الآخرين. استخدم صور التدريب أو آثار المختبر العامة أو بياناتك مع مراعاة الخصوصية.", references: [refs.nistForensics, refs.nistEvidence] },
  "dfir-3": { overview: "تساعد الخطوط الزمنية المحققين على رؤية العلاقات بين آثار متعددة. الهدف جعل تسلسل الدليل سهل المراجعة لا اختلاق قصة من بيانات ناقصة.", objectives: ["جمع ملاحظات مؤرخة في خط زمني شفاف.", "تحديد الفجوات والتعارضات في الدليل.", "ذكر الثقة والتفسيرات البديلة."], concepts: [{ title: "خط زمني متعدد المصادر", body: "يمكن جمع أدلة نظام الملفات والسجل والشبكة والتطبيق عند تسجيل مصدر وأساس الوقت لكل إدخال. تحفظ الإدخالات المتعارضة وتفحص بدلاً من حذفها." }, { title: "الثقة والفجوات", body: "قد تنتج فجوة البيانات من حدود الاحتفاظ أو انحراف الساعة أو تعطيل السجل أو عدم وقوع الحدث. صف الفجوة وأثرها على استنتاجك." }], safePractice: { title: "اربط آثاراً مقدمة", steps: ["اختر سيناريو DFIR بمجموعة بيانات صغيرة.", "ضع أربع ملاحظات بترتيب زمني واذكر مصادر آثارها.", "أضف فجوة وتفسيراً بديلاً ومصدراً تطلبه في تحقيق مصرح." ] }, review: { prompt: "ماذا تفعل عندما يبدو مصدران متعارضين؟", answer: "احفظ الملاحظتين، وتحقق من المناطق الزمنية وافتراضات الجمع، وسجل التعارض. لا تفرض استنتاجاً حتى يحل دليل إضافي التعارض أو يحدده." }, boundaries: "ابق داخل البيانات والقواعد التي يوفرها المختبر. لا تبحث في أنظمة عامة أو هويات حقيقية أو بيانات خارجية غير ذات صلة لإثراء حالة تدريبية.", references: [refs.nistForensics, { label: "مختبرات CyberDefenders للفريق الأزرق", url: "https://cyberdefenders.org/blue-team-labs/" }] },
  "dfir-4": { overview: "يوصل الملخص الجنائي ما يدعمه الدليل وما لا يدعمه وما ينبغي حدوثه لاحقاً. التقرير الأهم دقيق ومحدد ومفهوم لجمهوره.", objectives: ["كتابة ملخص تحقيق موجز.", "الفصل بين الملاحظات والتقييمات والتوصيات.", "إدراج القيود ومراجع الأدلة."], concepts: [{ title: "تقارير يقودها الدليل", body: "ابدأ بالنطاق والأسئلة ثم اعرض الملاحظات ومصادرها. يربط التقييم الملاحظات بحذر، وينبغي أن تناسب التوصيات درجة الثقة والسياق التشغيلي." }, { title: "الحدود احترافية", body: "قد تشمل الحدود سجلات مفقودة أو أنظمة غير متاحة أو فترة زمنية ضيقة أو نطاقاً مقيداً. تسميتها تجعل التقرير أنفع وتمنع افتراض يقين أكبر من الدليل." }], safePractice: { title: "اكتب ملخص حالة محدداً", steps: ["استخدم سيناريو تدريب مكتمل.", "اكتب نطاقاً بفقرة وثلاث ملاحظات بمصادرها وتقييماً وحدين.", "اختم بخطوة دفاعية كحفظ السجلات أو مراجعة ضبط وصول من دون ادعاء إسناد غير مدعوم." ] }, review: { prompt: "لماذا يجب تضمين القيود في الملخص الجنائي؟", answer: "لأنها تحدد ما يدعمه الدليل وتساعد صناع القرار على فهم عدم اليقين والفجوات والحاجة إلى عمل إضافي مصرح." }, boundaries: "لا تدرج بيانات شخصية أو بيانات اعتماد أو تفاصيل حالات حقيقية في Portfolio عام. استخدم ملخصات تدريبية منقحة فقط ما لم تملك إذناً صريحاً للمشاركة.", references: [refs.nistForensics, refs.nistEvidence] },
  "cloud-1": { overview: "أمن السحابة مسؤولية مشتركة؛ يدير الموفر والعميل وأحياناً أطراف أخرى طبقات مختلفة، لذا يعتمد مالك الضبط على نموذج الخدمة وتهيئتها.", objectives: ["مقارنة المسؤوليات عبر نماذج الخدمة.", "تحديد مجالات التهيئة التي يتحكم بها العميل.", "شرح أن استخدام خدمة سحابية لا ينقل كل المخاطر."], concepts: [{ title: "المسؤوليات تتغير حسب الخدمة", body: "قد يدير الموفر البنية المادية والخدمات المدارة، فيما يبقى العميل مسؤولاً عن الهويات وتصنيف البيانات والتهيئة واستخدام الخدمات. تحقق من الحدود في التوثيق الرسمي للخدمة." }, { title: "بنية الأمن", body: "ينبغي أن يحدد التصميم السحابي الأصول والهويات وتدفقات البيانات والسجلات والنسخ الاحتياطية وإدارة المفاتيح ومسارات التعافي لتوزيع الضوابط ومراقبتها." }], safePractice: { title: "أنشئ خريطة مسؤوليات", steps: ["استخدم تطبيق مشاركة ملفات خيالياً في بيئة سحابية تدريبية.", "أنشئ عمودين: مسؤوليات الموفر ومسؤوليات العميل.", "حدد ثلاثة مجالات تتحقق منها في توثيق الموفر قبل النشر." ] }, review: { prompt: "لماذا تعد عبارة «موفر السحابة يؤمن كل شيء» غير دقيقة؟", answer: "يدير الموفر والعميل طبقات مختلفة. يحتفظ العميل غالباً بمسؤولية الهوية والبيانات والتهيئة واستخدام الخدمات، وتختلف الحدود وفق النموذج والعقد." }, boundaries: "استخدم حسابات أو اشتراكات أو بيئات معزولة أو فصولاً مخولاً للوصول إليها فقط. اتبع الشروط وتنبيهات التكلفة وتعليمات تنظيف الموارد.", references: [refs.cisaCloud, refs.nistCloud] },
  "cloud-2": { overview: "الهوية هي مستوى التحكم في أمن السحابة. أقل الصلاحيات تعني منح الوصول اللازم لمهمة مبررة فقط ولأقصر مدة عملية مع ملكية قابلة للمراجعة.", objectives: ["وصف أقل الصلاحيات وفصل الواجبات.", "تحديد مخاطر الوصول الواسع أو المشترك.", "إنشاء قائمة تحقق بسيطة لمراجعة الوصول."], concepts: [{ title: "أقل الصلاحيات", body: "ابدأ بالمهمة والمورد والإجراءات والمدة. فضّل الهويات المسماة والأدوار المحددة على بيانات الاعتماد المشتركة وراجع الوصول بعد تغير الدور أو المشروع." }, { title: "دفاع متعدد الطبقات للهوية", body: "تعمل المصادقة القوية وتصميم الأدوار ومسارات الموافقة والسجل والمراجعة الدورية معاً. يخلق دور المدير الواسع سطح ضرر كبيراً عند إساءة استخدامه أو اختراقه." }], safePractice: { title: "راجع دوراً خيالياً", steps: ["استخدم سياسة دور نموذجية من دورة سحابية أو اكتب سياسة خيالية.", "اذكر المهمة والإجراءات المطلوبة وأي صلاحيات تبدو أوسع منها.", "اقترح مالك مراجعة وتاريخ انتهاء أو مراجعة." ] }, review: { prompt: "ما السؤال الذي يسبق منح صلاحية؟", answer: "ما المهمة المحددة التي تحتاج هذا الإجراء على هذا المورد لهذه المدة؟ يربط السؤال الوصول بحاجة مشروعة ويكشف الاتساع غير الضروري." }, boundaries: "لا تطلب أو تعدل أو تختبر الوصول في حساب سحابي لشخص آخر. تدرب في بيئات الموفر المعزولة أو مستأجري الفصول أو الحسابات التي تديرها.", references: [refs.csa, { label: "Microsoft Learn للأمن", url: "https://learn.microsoft.com/en-us/security/" }] },
  "cloud-3": { overview: "الأسرار والتهيئة مواد أمنية تشغيلية. عامل المفاتيح والرموز وكلمات المرور وتفاصيل الاتصال الحساسة كبيانات محمية، ولا تدمجها في الشيفرة أو السجلات.", objectives: ["التعرف إلى مسارات تعرض الأسرار الشائعة.", "وصف مبادئ التعامل الآمن مع التهيئة.", "إنشاء قائمة مراجعة تهيئة غير حساسة."], concepts: [{ title: "دورة حياة السر", body: "يحتاج السر إلى إنشاء وتخزين واستخدام وتدوير وإلغاء منضبط. لا ينبغي إيداعه في التحكم بالمصدر أو نسخه إلى لقطات شاشة أو مشاركته في ملاحظات غير محمية." }, { title: "مراجعة التهيئة", body: "راجع التعرض العام وربط الهوية والتشفير والسجل والاحتفاظ والنسخ الاحتياطية والملكية. سجل الحالة المقصودة وتحقق منها في البيئة المصرح بها." }], safePractice: { title: "افحص قائمة نشر خيالية", steps: ["استخدم تهيئة نموذجية بقيم بديلة فقط.", "حدد موضع تخزين السر والسجلات التي قد تكشفه عرضاً.", "اكتب ثلاثة ضوابط تقلل الخطر من دون وضع بيانات اعتماد حقيقية في ملاحظاتك." ] }, review: { prompt: "لماذا يعد وجود سر في مستودع شيفرة خطراً حتى لو كان خاصاً؟", answer: "قد يتغير الوصول، وقد تبقى النسخ والتاريخ، وقد تظهر الأسرار في السجلات أو النسخ الاحتياطية أو لدى المتعاونين أو عند النشر لاحقاً. استخدم إدارة أسرار معتمدة ودوّر القيم المكشوفة." }, boundaries: "لا تلصق مفاتيح API أو كلمات المرور أو رموز الوصول أو البيانات الشخصية أو تهيئة العملاء الحقيقية في Cyber 4 Ever. استخدم قيماً بديلة وألغِ أي سر كشف بالخطأ عبر الموفر المناسب.", references: [refs.secrets, refs.csa] },
  "cloud-4": { overview: "مراجعة الضوابط عملية منظمة لمقارنة الحالة المقصودة بالحالة الفعلية في نطاق مصرح، ثم توثيق الفجوات والمالكين وخطوات المتابعة الدفاعية.", objectives: ["إنشاء قائمة تحقق دفاعية للضوابط.", "ربط كل ضبط بمالك ودليل مراجعة.", "تمييز فجوة تهيئة من ادعاء اختراق."], concepts: [{ title: "قائمة تحقق قابلة للمراجعة", body: "تذكر القائمة الأصل أو الضبط والحالة المقصودة ومالكها ومصدر الدليل وتاريخ المراجعة. تمنع العناوين العامة وتساعد على اتخاذ إجراء محدد." }, { title: "التحسين لا الاتهام", body: "تشير فجوة الضبط إلى حاجة للمراجعة أو المعالجة، لا إلى اتهام شخص أو إثبات تعرض. تحقّق من السياق والشروط والمسؤول قبل الاستنتاج." }], safePractice: { title: "أنشئ قائمة تحقق تدريبية", steps: ["اختر بيئة سحابية تدريبية أو بنية خيالية.", "سجل خمسة ضوابط مثل الهوية والسجل والتشفير والنسخ الاحتياطي وإدارة الأسرار.", "أضف لكل ضبط مالكاً ودليلاً مطلوباً وخطوة متابعة دفاعية." ] }, review: { prompt: "ما فائدة ربط الضبط بمالك ودليل؟", answer: "يحول المراجعة من انطباع عام إلى عمل قابل للتحقق: يعرف المالك ما يجب مراجعته ويعرف القارئ ما الذي يدعم الحالة المسجلة." }, boundaries: "لا تراجع إعدادات إنتاجية أو حسابات لا تديرها. استخدم بيئة تدريبية أو نموذجاً خيالياً وتجنب جمع الأسرار أو بيانات العملاء.", references: [refs.nistCloud, refs.csa] },
};

export const arabicConceptCards = [
  { tag: "ويب", title: "المصادقة", detail: "تثبت المصادقة الهوية؛ ويقرر التفويض ما الذي تستطيع هذه الهوية فعله." },
  { tag: "DFIR", title: "سلامة الدليل", detail: "تحفظ الملاحظة الجيدة المصدر وتفصل بين المشاهدات والاستنتاجات." },
  { tag: "SOC", title: "فرز التنبيهات", detail: "يحتاج التنبيه إلى سياق؛ ولا يثبت الحادث بمفرده." },
  { tag: "سحابة", title: "أقل الصلاحيات", detail: "امنح الحد الأدنى من الوصول اللازم للمهمة وراجعه دورياً." },
];

export const arabicSafeLabs = [
  { name: "OWASP Juice Shop", url: "https://owasp.org/www-project-juice-shop/", description: "تطبيق ضعيف عمداً للتوعية والتدريب في أمن تطبيقات الويب.", tag: "ويب", fit: "ابدأ بفهم HTTP والمصادقة ومفاهيم مخاطر OWASP." },
  { name: "OWASP WebGoat", url: "https://owasp.org/www-project-webgoat/", description: "دروس موجهة تشرح نقطة الضعف ومعالجتها الدفاعية في تطبيق تعليمي معزول.", tag: "ويب", fit: "استخدمه لدروس الويب المنظمة ومناقشة المعالجة." },
  { name: "PortSwigger Web Security Academy", url: "https://portswigger.net/web-security", description: "مختبرات داخل المتصفح صممت لتعلم أمن الويب المصرح به.", tag: "ويب", fit: "استخدمه بعد الأساسيات لتعزيز موضوعات أمن التطبيقات المركزة." },
  { name: "TryHackMe", url: "https://tryhackme.com/", description: "غرف تعلم موجهة؛ اختر المسارات التعليمية واتبع قواعد كل غرفة.", tag: "موجه", fit: "مناسب لممارسة تدريجية مناسبة للمبتدئين عبر مجالات متعددة." },
  { name: "Hack The Box Academy", url: "https://academy.hackthebox.com/", description: "وحدات منظمة للأسس النظرية والعملية ضمن سياق مختبر.", tag: "موجه", fit: "مناسب لخطط التقدم ذات الأهداف المحددة من المزود." },
  { name: "pwn.college", url: "https://pwn.college/", description: "منصة جامعية للتعليم العملي في الأمن السيبراني بقواعد للمتعلمين.", tag: "أساسيات", fit: "مناسب للحوسبة الأساسية والتعلم القائم على التحدي؛ احترم قواعد مشاركة الحلول." },
  { name: "CyberDefenders", url: "https://cyberdefenders.org/blue-team-labs/", description: "سيناريوهات فريق أزرق عبر المتصفح للتدرب على DFIR والصيد التهديدي والعمليات الأمنية.", tag: "SOC / DFIR", fit: "استخدم الآثار المقدمة للتدرب على الفرز والخطوط الزمنية وملاحظات الأدلة." },
  { name: "Microsoft Learn Security", url: "https://learn.microsoft.com/en-us/security/", description: "مسارات تعلم أمنية من المزود ووحدات تدريب وبيئات معزولة مختارة.", tag: "سحابة", fit: "مناسب لمفاهيم أمن Microsoft والهوية والسحابة في سياقات موفر الخدمة." },
  { name: "AWS Skill Builder", url: "https://aws.amazon.com/training/digital/immersive-learning/", description: "تجارب موجهة وبيئات تعلم آمنة لـ AWS؛ وقد يتغير التوفر باختلاف الحساب والدورة.", tag: "سحابة", fit: "استخدمه لممارسة بنية السحابة والتهيئة بعد مراجعة شروط التكلفة والوصول." },
];

export const copy = {
  en: {
    language: "العربية", languageShort: "AR", brandTagline: "Cybersecurity, forever", dashboard: "Learning dashboard", roadmaps: "Roadmaps", labs: "Safe labs", planner: "Study planner", journal: "Lab journal", portfolio: "Student portfolio", library: "Concept library", ethics: "Responsible practice", private: "Private on this device", privateNote: "No accounts. No tracking.",
    heroTitle: "Build your path with confidence. Practice within safe boundaries.", heroBody: "A focused home for cybersecurity study, authorized labs, and real learning evidence.", startPath: "Start a path", reviewPlan: "Review today’s plan", progress: "progress", completedMinutes: "completed learning minutes", completedModules: "completed modules", activeTracks: "active tracks", learner: "Responsible learner", privacyFirst: "Privacy first", nowPath: "NOW ON YOUR PATH", pathMastery: "Path mastery", explore: "Explore modules", learningRecord: "LEARNING RECORD", keyMoments: "Your key moments", recordStart: "Your personal learning record starts here.", openJournal: "Open lab journal", principle: "PLATFORM PRINCIPLE", principleBody: "Learn with curiosity; practice with authorization; document honestly.", readBoundaries: "Read boundaries",
    pathsRoles: "PATHS BUILT FOR REAL ROLES", learnSequence: "Learn in sequence, not in fragments.", roadmapsBody: "Open a lesson, work through its concepts and safe practice, then record your completion. Every completion mark stays on your device.", complete: "complete", learningRule: "Learning rule", ruleBody: "Understand the defensive control before any experiment.", activeLesson: "ACTIVE LESSON", closeLesson: "Close lesson", endCan: "BY THE END, YOU CAN", coreConcept: "CORE CONCEPT", safePractice: "SAFE PRACTICE", checkUnderstanding: "CHECK YOUR UNDERSTANDING", authorization: "Authorization boundary", officialReferences: "OFFICIAL REFERENCES", markIncomplete: "Mark as not complete", markComplete: "Mark lesson complete",
    labsKicker: "PRACTICAL, BUT RESPONSIBLE", labsTitle: "Labs made for learning, not real-world targets.", labsBody: "Choose a resource that matches your current lesson. The platform links only to official, purpose-built training resources and keeps authorization non-negotiable.", beforeLab: "Before opening any lab", beforeLabBody: "Read the provider rules, use your own account, confirm any cost or access terms, and never redirect an exercise toward a real site or network.", usagePolicy: "Usage policy", bestFit: "Best fit", approved: "Approved learning resource", openResource: "Open official resource", afterSession: "AFTER EACH SESSION", retainTitle: "Turn the session into knowledge you can retain.", retainBody: "Record the environment, what you observed, and why the defensive control works. Do not store passwords or sensitive data in notes.",
    planKicker: "SMALL PLAN, STEADY PROGRESS", planTitle: "Design today’s session.", planBody: "You do not need long hours. Choose one bounded task, a realistic time, and record what you complete.", tasksComplete: "tasks complete", addSession: "ADD SESSION", clearSession: "One clear session beats a long list.", whatLearn: "What will you learn?", learnPlaceholder: "e.g. Understand secure cookies", path: "Path", minutes: "Minutes", savePlan: "Save to today’s plan", sessions: "TODAY’S SESSIONS", doCheck: "Do, then check it off.", addFirst: "Add a realistic first session for today.", removeTask: "Remove task", planPrivate: "Your plan remains in this browser only. You can export your record from the lab journal whenever you wish.",
    journalKicker: "YOUR PRACTICAL MEMORY, YOURS", journalTitle: "Record what you learned, not what you assume.", journalBody: "A private journal turns a lab session into a simple, reviewable note. Never record secrets, real data, or steps outside a lab scope.", newNote: "NEW NOTE", remember: "What will you remember?", clearTitle: "Clear title", titlePlaceholder: "e.g. How session cookies are verified", environment: "Training environment", environmentPlaceholder: "OWASP Juice Shop / Local lab", observation: "What did you observe, and what is the defensive control?", observationPlaceholder: "Write a specific, defensive learning note...", saveLocal: "Save locally", noSensitive: "Do not put sensitive data or access tokens here.", yourRecord: "YOUR RECORD", notes: "notes", export: "Export", import: "Import", noteStart: "One good note is the start of an honest portfolio.", delete: "Delete",
    evidenceClaims: "EVIDENCE, NOT CLAIMS", portfolioTitle: "A portfolio that reflects what you actually did.", portfolioBody: "Add genuine projects, certificates, and lab milestones. The platform labels an item evidence-linked only when you supply a reviewable external HTTPS link.", addItem: "ADD ITEM", evidenceReview: "Make your evidence reviewable.", type: "Type", project: "Project", certificate: "Certificate", labMilestone: "Lab milestone", whatBuilt: "What did you learn or build?", evidenceLink: "Evidence link (optional)", markEvidence: "Mark this item as evidence-linked", addPortfolio: "Add to portfolio", studentProfile: "Student profile", learnerName: "Cyber 4 Ever Learner", noCertificates: "This view grants no certificates and does not verify identity; it is a space to present your real evidence only.", realMilestone: "Add a real milestone.", milestoneBody: "Start with a project, a verifiable certificate, or a lesson from an authorized lab.", evidenceLinked: "Evidence-linked", viewEvidence: "View evidence", noExternal: "No external link", remove: "Remove",
    understand: "UNDERSTAND BEFORE YOU MEMORIZE", conceptsTitle: "Short, useful, defensive concepts.", conceptsBody: "These cards build a shared language for your learning paths. Review the idea, then apply it only in an authorized lab.", foundation: "Foundation concept", openRoadmaps: "Open roadmaps", primaryRefs: "PRIMARY REFERENCES", maintained: "Learn from sources that maintain themselves.", refsBody: "The paths are informed by NICE work roles, OWASP guidance, and purpose-built educational environments. Read the source when you need more depth.", boundariesKicker: "CLEAR BOUNDARIES PROTECT LEARNING", ethicsTitle: "Authorization is the beginning of professional skill.", ethicsBody: "Cyber 4 Ever supports defensive, methodical learning. It does not run scans, collect targets, or provide instructions for targeting real systems.", golden: "The golden rule", goldenQuote: "If you do not have explicit, specific authorization, do not test.", goldenBody: "An authorized scope protects you and others, and makes your learning professionally durable.", context: "Context", decision: "Decision", allowed: "Allowed after reading its rules", allowedScope: "Allowed within authorization", notAllowed: "Not allowed", doNotStore: "Do not collect or store", privacyPromise: "Privacy promise", privacyBody: "No sign-in, no user analytics, and no server storing your journal or portfolio. You can remove data through browser storage or export it first.",
  },
  ar: {
    language: "English", languageShort: "EN", brandTagline: "الأمن السيبراني، إلى الأبد", dashboard: "لوحة التعلّم", roadmaps: "المسارات", labs: "المختبرات الآمنة", planner: "مخطط الدراسة", journal: "دفتر المختبر", portfolio: "ملف الطالب", library: "مكتبة المفاهيم", ethics: "الممارسة المسؤولة", private: "خاص على هذا الجهاز", privateNote: "لا حسابات. لا تتبع.",
    heroTitle: "ابنِ مسارك بثقة. وتدرّب ضمن حدود آمنة.", heroBody: "مساحة مركزة لدراسة الأمن السيبراني والمختبرات المصرح بها وأدلة التعلم الحقيقية.", startPath: "ابدأ مساراً", reviewPlan: "راجع خطة اليوم", progress: "التقدم", completedMinutes: "دقائق تعلم مكتملة", completedModules: "وحدات مكتملة", activeTracks: "مسارات نشطة", learner: "متعلم مسؤول", privacyFirst: "الخصوصية أولاً", nowPath: "مسارك الحالي", pathMastery: "إتقان المسار", explore: "استكشف الوحدات", learningRecord: "سجل التعلّم", keyMoments: "لحظاتك المهمة", recordStart: "يبدأ سجل تعلمك الشخصي من هنا.", openJournal: "افتح دفتر المختبر", principle: "مبدأ المنصة", principleBody: "تعلّم بفضول؛ وتدرّب بتفويض؛ ووثّق بأمانة.", readBoundaries: "اقرأ الحدود",
    pathsRoles: "مسارات مبنية لأدوار واقعية", learnSequence: "تعلّم بتسلسل، لا على شكل أجزاء متفرقة.", roadmapsBody: "افتح الدرس، واعمل على مفاهيمه وتطبيقه الآمن، ثم سجّل إتمامه. تبقى كل علامات الإتمام على جهازك.", complete: "مكتمل", learningRule: "قاعدة التعلّم", ruleBody: "افهم الضبط الدفاعي قبل أي تجربة.", activeLesson: "الدرس الحالي", closeLesson: "إغلاق الدرس", endCan: "بنهاية الدرس ستتمكن من", coreConcept: "مفهوم أساسي", safePractice: "تطبيق آمن", checkUnderstanding: "تحقق من فهمك", authorization: "حدود التفويض", officialReferences: "مراجع رسمية", markIncomplete: "إلغاء إتمام الدرس", markComplete: "وضع علامة إتمام الدرس",
    labsKicker: "عملي، ولكن بمسؤولية", labsTitle: "مختبرات صممت للتعلم، لا لاستهداف الأنظمة الحقيقية.", labsBody: "اختر مورداً يناسب درسك الحالي. تربط المنصة موارد تدريب رسمية مصممة لهذا الغرض فقط، ويظل التفويض شرطاً ثابتاً.", beforeLab: "قبل فتح أي مختبر", beforeLabBody: "اقرأ قواعد الموفر، واستخدم حسابك الخاص، وتحقق من شروط التكلفة أو الوصول، ولا توجّه أي تمرين نحو موقع أو شبكة حقيقية.", usagePolicy: "سياسة الاستخدام", bestFit: "الأنسب", approved: "مورد تعلم معتمد", openResource: "افتح المورد الرسمي", afterSession: "بعد كل جلسة", retainTitle: "حوّل الجلسة إلى معرفة تبقى معك.", retainBody: "سجل البيئة وما لاحظته وسبب فاعلية الضبط الدفاعي. لا تخزن كلمات المرور أو البيانات الحساسة في الملاحظات.",
    planKicker: "خطة صغيرة، تقدم ثابت", planTitle: "صمّم جلسة اليوم.", planBody: "لا تحتاج ساعات طويلة. اختر مهمة محددة ووقتاً واقعياً وسجّل ما تنجزه.", tasksComplete: "مهام مكتملة", addSession: "أضف جلسة", clearSession: "جلسة واضحة أفضل من قائمة طويلة.", whatLearn: "ماذا ستتعلم؟", learnPlaceholder: "مثال: فهم ملفات الارتباط الآمنة", path: "المسار", minutes: "الدقائق", savePlan: "احفظ في خطة اليوم", sessions: "جلسات اليوم", doCheck: "نفّذها ثم علّم عليها.", addFirst: "أضف أول جلسة واقعية لليوم.", removeTask: "حذف المهمة", planPrivate: "تبقى خطتك في هذا المتصفح فقط. يمكنك تصدير سجلك من دفتر المختبر متى شئت.",
    journalKicker: "ذاكرتك العملية، ملكك", journalTitle: "سجّل ما تعلّمته، لا ما تفترضه.", journalBody: "يحوّل الدفتر الخاص جلسة المختبر إلى ملاحظة بسيطة قابلة للمراجعة. لا تسجل أسراراً أو بيانات حقيقية أو خطوات خارج نطاق المختبر.", newNote: "ملاحظة جديدة", remember: "ما الذي ستتذكره؟", clearTitle: "عنوان واضح", titlePlaceholder: "مثال: كيفية التحقق من جلسات ملفات الارتباط", environment: "بيئة التدريب", environmentPlaceholder: "OWASP Juice Shop / مختبر محلي", observation: "ماذا لاحظت، وما هو الضبط الدفاعي؟", observationPlaceholder: "اكتب ملاحظة تعلم دفاعية ومحددة...", saveLocal: "احفظ محلياً", noSensitive: "لا تضع بيانات حساسة أو رموز وصول هنا.", yourRecord: "سجلك", notes: "ملاحظات", export: "تصدير", import: "استيراد", noteStart: "ملاحظة جيدة واحدة هي بداية ملف إنجاز صادق.", delete: "حذف",
    evidenceClaims: "أدلة، لا ادعاءات", portfolioTitle: "ملف يعكس ما أنجزته فعلاً.", portfolioBody: "أضف مشاريع وشهادات ومحطات مختبر حقيقية. تصف المنصة العنصر بأنه مرتبط بدليل فقط عند إضافة رابط HTTPS خارجي قابل للمراجعة.", addItem: "أضف عنصراً", evidenceReview: "اجعل دليلك قابلاً للمراجعة.", type: "النوع", project: "مشروع", certificate: "شهادة", labMilestone: "محطة مختبر", whatBuilt: "ماذا تعلمت أو بنيت؟", evidenceLink: "رابط الدليل (اختياري)", markEvidence: "ضع علامة أن العنصر مرتبط بدليل", addPortfolio: "أضف إلى الملف", studentProfile: "ملف الطالب", learnerName: "متعلم Cyber 4 Ever", noCertificates: "لا تمنح هذه الصفحة شهادات ولا تتحقق من الهوية؛ إنها مساحة لعرض أدلتك الحقيقية فقط.", realMilestone: "أضف محطة حقيقية.", milestoneBody: "ابدأ بمشروع أو شهادة قابلة للتحقق أو درس من مختبر مصرح.", evidenceLinked: "مرتبط بدليل", viewEvidence: "اعرض الدليل", noExternal: "لا يوجد رابط خارجي", remove: "إزالة",
    understand: "افهم قبل أن تحفظ", conceptsTitle: "مفاهيم دفاعية قصيرة ومفيدة.", conceptsBody: "تبني هذه البطاقات لغة مشتركة لمساراتك التعليمية. راجع الفكرة ثم طبقها في مختبر مصرح فقط.", foundation: "مفهوم أساسي", openRoadmaps: "افتح المسارات", primaryRefs: "مراجع أساسية", maintained: "تعلّم من مصادر تحدث محتواها بنفسها.", refsBody: "تستند المسارات إلى أدوار NICE وإرشادات OWASP وبيئات تعليمية مصممة لهذا الغرض. اقرأ المصدر عندما تحتاج إلى عمق أكبر.", boundariesKicker: "حدود واضحة تحمي التعلّم", ethicsTitle: "التفويض بداية المهارة المهنية.", ethicsBody: "تدعم Cyber 4 Ever التعلم الدفاعي والمنهجي. لا تشغل المنصة عمليات مسح ولا تجمع أهدافاً ولا تقدم تعليمات لاستهداف أنظمة حقيقية.", golden: "القاعدة الذهبية", goldenQuote: "إن لم يكن لديك تفويض صريح ومحدد، فلا تختبر.", goldenBody: "يحمي النطاق المصرح به الآخرين ويحميك ويجعل تعلمك مستداماً مهنياً.", context: "السياق", decision: "القرار", allowed: "مسموح بعد قراءة قواعده", allowedScope: "مسموح ضمن التفويض", notAllowed: "غير مسموح", doNotStore: "لا تجمع ولا تخزن", privacyPromise: "وعد الخصوصية", privacyBody: "لا تسجيل دخول ولا تحليلات مستخدمين ولا خادم يخزن دفترك أو ملفك. يمكنك حذف البيانات من تخزين المتصفح أو تصديرها أولاً.",
  },
} as const;
